### ISSUE TITLE
Unexpected warning (read_xlsx)

### ISSUE THREAD

**Issue by apalacio9502** [JanMarvin/openxlsx2#1012]
Hello,

In the new version 1.6 an unexpected warning appears when using read_xlsx. It is important to note that the Excel file only has one sheet.

As a recommendation, I think that the warning is not very clear, if the warning is expected I think the documentation should be improved.

```
file <- openxlsx2::read_xlsx(
    file = file.xlsx,
    skip_empty_cols = TRUE
 ) 

Warning message:
Found unknown folders in the input file:
[trash]

These folders are not yet processed by openxlsx2, but depending on what you want to do, this may not be fatal.
Most likely a file with these folders has not yet been detected. If you want to contribute to the development of the package, maybe just to silence this warning, please open an issue about unknown content folders and, if possible, provide a file via our Github or by mail. 
```
Regards,

**Comment by apalacio9502** [comment]
Hello,

Thank you for your prompt response. 

Responding to your question, it's notable that the files were created by  openxlsx2 library. The only aspect is that they undergo a process of loading and unloading to SharePoint using the Microsoft365 library. (I can confirm that the "trash" folder is created during the loading and unloading process to SharePoint.)



After examining the purpose of the warnings outlined here: https://github.com/JanMarvin/openxlsx2/pull/983/commits/db313262f25573265dbdf65ce73dce7a5a934ffa, I believe it's crucial to find a balance in determining when to issue a warning and when not to. I'm uncertain whether this warning would prove beneficial for the majority of users.

As a suggestion, I recommend incorporating a variable such as "verbose" that advanced Excel users could activate if they encounter any issues in the code. This adjustment would enable greater customization and control over the warnings generated.

Regards,

**Comment by JanMarvin** [comment]
A patch ignoring `[trash]` is in the development branch now. You can install it via `remotes` or `r-universe`. The fix will be part of the next release which will probably released to CRAN in a month or so.

For the time being you can silence the warning with e.g. `suppressWarnings()` or some other `tryCatch()` logic.
