### ISSUE TITLE
All columns between date columns get formatted as date columns

### ISSUE THREAD

**Issue by D3SL** [JanMarvin/openxlsx2#1023]
I just updated to v1.6 (R4.4.0) and found any columns located between two date columns will wind up being formatted as date columns when creating a workbook. 

```R
test_dt<-data.table(
  e=seq(ymd("2024-01-01"),ymd("2024-01-05"),1),
  a=letters[1:5],
  j=seq(ymd("2024-01-01"),ymd("2024-01-05"),1),
  b=c(letters[3:5],NA,NA),
  c=1:5,
  d=c(NA,NA,3,4,5),
  f=letters[1:5],
  g=c(letters[3:5],NA,NA),
  h=1:5,
  i=c(NA,NA,3,4,5)
)

test_wb<-wb_workbook()
test_wb<-wb_add_worksheet(test_wb,sheet="test_sheet1")
test_wb<-wb_add_worksheet(test_wb,sheet="test_sheet2")
test_wb<-wb_add_data(test_wb,test_dt,sheet="test_sheet1",na.strings = "")

wb_open(test_wb)
```

**Comment by JanMarvin** [comment]
I suspect that there’s a bug in this code:
https://github.com/JanMarvin/openxlsx2/blob/2de13e498cd48125e6cc35bba2e32e7a3005c516/R/write.R#L491-L501

This needs a check for consecutive columns because right now I think that the dim selection is something like `A2:C6`, but it should be `A2:A6,C2:C6`.

**Comment by JanMarvin** [comment]
Thanks, should be fixed now
