### ISSUE TITLE
NA string "" not an empty cell in 1.6

### ISSUE THREAD

**Issue by D3SL** [JanMarvin/openxlsx2#1024]
I just updated to v1.6 (R 4.4.0) and `na.strings = ""` is broken. Filters show `(Blanks)` but `=ISBLANK(cell)` returns false and ctrl+arrow behavior treats blanks as if they had content. 

```R
test_dt<-data.table(
char=rep(NA_character_,5),
number=rep(NA_complex_,5),
bool=rep(NA,5),
date=rep(NA_Date_,5)
)

test_wb<-wb_workbook()
test_wb<-wb_add_worksheet(test_wb,sheet="test_sheet1")
test_wb<-wb_add_data(test_wb,test_dt,sheet="test_sheet1",na.strings = "")

wb_open(test_wb)
```

**Comment by JanMarvin** [comment]
Hi @D3SL , thanks for your reports. Are these regressions aka did they work previously as expected? `na.strings =“”` initializes the cell as empty strings, which apparently is not blank for excel. But `na.strings = NULL` works.

**Comment by JanMarvin** [comment]
Okay, thanks. I’d like to close this issue if you can confirm that `NULL` works for you. To me it’s a spreadsheet issue. If I remember correctly, contains blanks checks in conditional formatting checks for string length greater 0. Something like this might work.

**Comment by JanMarvin** [comment]
This is how contains blank works:
https://github.com/JanMarvin/openxlsx2/blob/2de13e498cd48125e6cc35bba2e32e7a3005c516/R/conditional_formatting.R#L461

**Comment by D3SL** [comment]
I can confirm that NULL works. If that's backwards compatible with older versions and doesn't break anything else this is definitely closable.

**Comment by JanMarvin** [comment]
Thanks!
