### ISSUE TITLE
Print/save Excel (.xlsx) sheet to PDF using R

### ISSUE THREAD

**Issue by chuxinyuan** [JanMarvin/openxlsx2#1025]
<https://stackoverflow.com/questions/30942927/print-save-excel-xlsx-sheet-to-pdf-using-r>

I'm looking forward to the openxlsx2 package adding a function to do this.

[Here is an article](https://medium.com/@alexaae9/python-how-to-convert-excel-documents-to-pdf-files-1af340822837) that implements the above functionality, only in python.

**Comment by JanMarvin** [comment]
Hi @chuxinyuan , sorry, but that’s not planned and way beyond what this package can do and should be. 

If you don’t want to click in some spreadsheet software, your best chance would be to try to make use of libreoffice in headless mode, maybe this way it’s possible to print to pdf. [see here](https://stackoverflow.com/questions/30349542/command-libreoffice-headless-convert-to-pdf-test-docx-outdir-pdf-is-not)

With xl_open() or wb_open() you can open the file/workbook in spreadsheet software. From there it’s just a few clicks to print to pdf.
