### ISSUE TITLE
include argument check.names when reading files

### ISSUE THREAD

**Issue by guidohooiveld** [JanMarvin/openxlsx2#1050]
I am switching to the use of `openxlsx2` (from `openxlsx`).

Adapting my `openxlsx`-based workflow is straight-forward, but I noticed that, when reading/importing Excel files using `read_xlsx`, a corresponding argument for `check.names` seems to be missing.

Small feature request: if so, could such check be implemented as well?

https://github.com/ycphs/openxlsx/blob/6b0cf0f78d7bc321e1bc59c14b53ebac26a491b8/R/readWorkbook.R#L542-L551

**Comment by JanMarvin** [comment]
Hi @guidohooiveld , I have no real opinion. Guess we could add something like this. Do you want to prepare a PR?

**Comment by guidohooiveld** [comment]
Hi, thanks for your quick reply.
Unfortunately, to be honest, preparing a PR goes above my skill set.... I know quite well how to use R, but changing/testing functions and knowing the inner works of version control and PRs with GitHub is not something I have done before. Sorry.

**Comment by JanMarvin** [comment]
No problem, I was just offering ... I've added a PR. Is this what you wanted? I was unable to find a test in `openxlsx2` hence, I was a little bit unsure what precisely you are looking for.

```R
remotes::install_github("JanMarvin/openxlsx2#1051")
```

**Comment by guidohooiveld** [comment]
Thanks for adding this so quickly; tested with some xlsx-files that had 'R-invalid' characters in columns names, and these were 'corrected' when imported.

**Comment by JanMarvin** [comment]
Thanks, merged!
