### ISSUE TITLE
Add an option to scale the font size of the header/footer with the document

### ISSUE THREAD

**Issue by jploetner** [JanMarvin/openxlsx2#1085]
Hello,

when creating an excel file I scale the content to fit on one page with `wb_page_setup(fit_to_width = 1)` for printing, which works fine. The problem is that the font sizes of the header and footer are too big, because per default they are not scaled as well. In Excel there is an option in View -> Page Layout -> click on the header or footer -> Design called `Scale with document`. If you check it, then the header/footer are automatically scaled as well. But right now there is no argument in `openxlsx2` to change it.

If you create the following file:
```r
library(openxlsx2)

wb <- wb_workbook() %>%
  wb_add_worksheet(header = c(NA, "Header", NA), orientation = "landscape") %>%
  wb_page_setup(fit_to_width = 1) %>%
  wb_add_data(x = as.data.frame(matrix(1:500, ncol = 25)))

wb$open()
```

you can see in the following screenshot that "Header" is larger than the rest of the document (Unfortunately, I wasn't able to change the language of my Excel at the moment):

![grafik](https://github.com/user-attachments/assets/87f46d54-298c-4501-915e-152680654122)

However, if you check `Scale with document` "Header" is scaled as well:

![grafik](https://github.com/user-attachments/assets/6b8dde5e-d1bd-4715-b462-c9fd9b496001)

It would be great, if an option to change that `Scale with document`-parameter could be added to ensure that the whole document and not just the body is scaled when fitting a worksheet to a fixed number of pages.

**Comment by JanMarvin** [comment]
Hi @jploetner , thanks for the report and I appreciate the screenshots (never would have guessed the impact). I have prepared a PR which should solve this.
