### ISSUE TITLE
Named range names to begin with numbers

### ISSUE THREAD

**Issue by cc20002002** [JanMarvin/openxlsx2#1095]
Excel does not accept named range names starting with numbers. Openxlsx2 allows named range names to begin with numbers. Then the saved xlsx file will lose the named range. 

To reproduce the Problem 

  1. Create an empty wb object
  
  2. Create a named range with a name like '15000'
  
  3. save the object into an xlsx file then open it with excel

**Comment by JanMarvin** [comment]
Hi @cc20002002 , thanks for the report. I will add a check for this, but unfortunately there are plenty of other ways to create a broken output file.
