### ISSUE TITLE
[docs] Colummn type guessing

### ISSUE THREAD

**Issue by raffaem** [JanMarvin/openxlsx2#1117]
`readxl::read_excel` guesses column types based on the value of the first `guess_max` (an argument of the function) of its cells ([reference](https://readxl.tidyverse.org/articles/cell-and-column-types.html#type-guessing))

This causes problems in importing when a numeric cell way down in my Excel file is silently converted into a boolean, without any warning of any sort.

This problem doesn't happen with openxlsx2.

Can you specify in the documentation how openxlsx2 guesses column types?

My understanding is that Excel only provides cell types, not column types.

I was reading the "convert input to guessed type" in [the documentation](https://cran.r-project.org/web/packages/openxlsx2/vignettes/openxlsx2_read_to_df.html) but it doesn't say much about how it guesses.

**Comment by JanMarvin** [comment]
Hi @raffaem , we have a function `guess_column_type()` iirc. It tries to guess the column type based on all values in the character column. The types are based on our internal checks. Does the cell look like a bool, a number, or a date.
Is there any specific reason why you want documentation improved on this specific topic? After all the code is open and you can simply have a look. I might add a sentence to the `wb_to_df()` documentation, but that would be more on the general side of things.
