### ISSUE TITLE
include `current_sheet()`, `next_sheet()` waivers/private fields

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#113]
I'm thinking about adding some "last action" entry for `wbWorkbook`, but like to discuss this previously.

My rationale is the following:
```R
wb <- wb_workbook()
wb <- wb_add_worksheet("test") # add wb$last$sheet <- "test"
```

## why
We could use `$last` for different things like `sheet` but also `dims`. I was thinking about this, when playing around with borders. Previous functions had options for borders surrounding some area. Right now, we do not now which area was written. If we would store this via `wb$last$dims` we could simply use the dims to build our borders on this.

### current
So all calls following this call can access `wb$last$sheet` to work on this sheet. So calling
```R
writeData(wb, x = mtcars)
# is identical to
writeData(wb, sheet = "test", x = mtcars)
```

### future
Once `writeData` becomes something like `wb_write_data` the pipe would look something like this:
```R
wb <- wb_workbook() |>
  wb_add_worksheet("Sheet 1") |>
  wb_write_data(x = mtcars)
```

The chain would be:
```R
wb <- wb_workbook()$
   add_worksheet("Sheet 1")$
   write_data(x = mtcars)
```

**Comment by JanMarvin** [comment]
Yes, that's mostly what I had in mind, just a bit more elaborated. I would like to have the opportunity to pass down a few more parameters like written dims. That would be helpful identifying the required borders for high level border functions, or for something like coloring the cell background of every second column.
E.g. add data to worksheet, call border function, border function gets dims, sets border style for top left different than for top right or bottom

**Comment by jmbarbone** [comment]
I _think_ a `next_sheet()` would also be **good**

```r
wb$add_worksheet = function(sheet = next_sheet(), ...) {
  private$current_sheet <- sheet
}

# add attributes
# check with inherits(x, what = "wb_waiver")
# get option with isTRUE(attr(x, "next_sheet"))
next_sheet <- function() { 
  structure(list(), class = "wb_waiver", next_sheet = TRUE) 
}

current_sheet - function() { 
  structure(list(), class = "wb_waiver", current_sheet = TRUE)
}
```

so that I can do:

```r
data <- data.frame(x = 1)
wb_workbook$add_worksheet()$add_data(x = data)$add_worksheet()$add_worksheet()
```
