### ISSUE TITLE
`types` argument in `wb_to_df` uses positional value instead of named value

### ISSUE THREAD

**Issue by maximecharriere** [JanMarvin/openxlsx2#1146]
In the doc of `wb_to_df {openxlsx2}` it's written to use the `types` argument like this:  
``` 
wb_to_df(wb1, cols = c(2, 5), types = c("Var1" = 0, "Var3" = 1))
```

Therefore, I guessed that the "VarX" names in the list can be in any order, and that the var name will be used to found the corresponding column to convert.  
I found out that it's not the variable name that is used, but it's position in the list. 
**Exemple**:  
If I have this dataframe:  
| Var1 | Var3 | Var2 |
|---|---|---|
|"abc"|123|"ghi"|
|"def"|456|987|

And I run `wb_to_df(wb1, types = c("Var1" = 0, "Var2" = 0, "Var3" = 1))`, the types of the columns "Var3" and "Var2" will be inverted.  

As I know the name (id) of each columns of my dataframe, but not it's position, I can't use the conversion tool included in `wb_to_df`.  

I would suggest a Documentation Update to clarify how the `types` argument is used, or even a way to use the variable name instead of its position in the named numeric list.  

This request concern this line of code:  
https://github.com/JanMarvin/openxlsx2/blob/b3f915054625c5314ee028a479443062ea1ec712/R/read.R#L637

---
Also, another suggestion would be to be able to give a list of types not of the same size of the dataframe. Therefore, If I want to force the type of some columns, but let openxlsx2 guess the type of the remaining columns, I can do this:

If I have this dataframe:  
| Var1 | Var3 | Var2 |
|---|---|---|
|"abc"|123|"ghi"|
|"def"|456|987|

And I run `wb_to_df(wb1, types = c("Var1" = 0, "Var3" = 1))` to let openxlsx2 guess the type of the "var2".

**Comment by JanMarvin** [comment]
Thanks for the report @maximecharriere ! I have opened a PR in #1147 which should handle your request. Could you give this a try?

``` r
library(openxlsx2)

df <- data.frame(
  Var1 = c("abc", "def"),
  Var3 = c(123, 456),
  Var2 = c(99999, 987)
)
df$Var2 <- labelled::labelled(df$Var2, c("ghi" = 99999))

wb1 <- wb_workbook()$add_worksheet()$add_data(x = df)

if (interactive()) wb1$open()

x <- wb_to_df(wb1, types = c("Var1" = "character", "Var3" = "numeric"))
x
#>   Var1 Var3 Var2
#> 2  abc  123  ghi
#> 3  def  456  987
```

**Comment by JanMarvin** [comment]
The PR was merged into main

**Comment by maximecharriere** [comment]
Perfect! Thank you Marvin!
