### ISSUE TITLE
Adding a table to xlsx file with previously deleted table causes id duplication

### ISSUE THREAD

**Issue by mlell** [JanMarvin/openxlsx2#1151]
Sometimes, openxlsx2 seems to give duplicate IDs to Excel Tables, which causes an invalid file format error by excel.

See the video or the steps below to reproduce:

[openxlsx.webm](https://github.com/user-attachments/assets/77bf9666-3581-45cd-bba8-048bea2af446)

1. Create an XLSX file using Excel and create two [tables](https://support.microsoft.com/en-us/office/overview-of-excel-tables-7ab0bb7d-3a9e-4b56-a3c9-6c94334e492c)
2. Save, close, and reopen the file
3. Delete the table that you have created first using "Table Tools" >"Convert to region" (if I translated correctly from German)
4. Save and close
5. Open using R and add another data table using `wb$add_data_table()`. A table is created with ID 2, but that ID is also used by the second table that was created in Excel before, which still exists
6. Save and open in Excel. It produces an error message offering to repair the file. 

Expected: Openxlsx should not create `<table>` tags in `xl/tables/*.xml` with an `id=` value that already exist in another xml file in the same folder

Test with openxlsx2 1.9.0.9000 (`acfdffd`) on Linux, R 4.2.2 Patched.

Code:

```R
# shorten XML output, remove contents of <table> and schema URLs
table_ids <- function(xml){
  xml <- sub(">.*</",">...</",xml)
  xml <- gsub("http.*?\"","http...",xml)
  xml
}

library(openxlsx2)
wb <- wb_load("Neuer Ordner/tabnaming.xlsx")
table_ids(wb$tables$tab_xml)

wb$add_data_table(1, data.frame(a=1, b=2), table_name = "test")
table_ids(wb$tables$tab_xml)

wb$save("Neuer Ordner/tabnaming.xlsx")
```

**Comment by JanMarvin** [comment]
Thanks for the report, @mlell ! Thanks for the video, this really helped to understand the issue. I have added a PR in #1152 that should fix this and ensure that unique table ids are used.

**Comment by mlell** [comment]
Thank you for tackling this so quickly! However, the test you provided does not seem to capture the problem. It also passes on the non-patched version. Also, the XLSX generated by the test behaves diffferently than the XLSX generated manually using excel. See example below. The problem occurs only with the manually generated  file. The two files also differ in file names that are created inside the XLSX archive

manually generated: 
`/xl/tables/table1.xml`:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
<table totalsRowShown="0" ref="A6:B8" displayName="Tabelle2" name="Tabelle2" xr:uid="{AC89B162-1804-4611-916F-C3FD6F8F4A5D}" id="2" xmlns:xr3="http://schemas.microsoft.com/office/spreadsheetml/2016/revision3" xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision" mc:Ignorable="xr xr3" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">](file:///C:/Users/lell/AppData/Local/Temp/7zOC3354D35/table1.xml#)
  <autoFilter ref="A6:B8" xr:uid="{ED4355E5-FFB2-42F2-9671-2213C93BEBCC}"/>
  <tableColumns count="2">](file:///C:/Users/lell/AppData/Local/Temp/7zOC3354D35/table1.xml#)
    <tableColumn name="Spalte1" xr3:uid="{FD9F5E32-240F-4A09-9E52-8CC7FF6CD2E9}" id="1"/>
    <tableColumn name="Spalte2" xr3:uid="{5A48773B-231C-4867-BC92-967D257EE43F}" id="2"/>
  </tableColumns>
  <tableStyleInfo name="TableStyleLight1" showColumnStripes="0" showRowStripes="1" showLastColumn="0" showFirstColumn="0"/>
</table>
```

generated using openxlsx2:
`/xl/tables/table2.xml`

```xml
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
<table totalsRowShown="0" totalsRowCount="0" ref="A1:E7" displayName="Table2" name="Table2" id="2" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <autoFilter ref="A1:E7"/>
  <tableColumns count="5">
    <tableColumn name="Sepal.Length" id="1"/>
    <tableColumn name="Sepal.Width" id="2"/>
    <tableColumn name="Petal.Length" id="3"/>
    <tableColumn name="Petal.Width" id="4"/>
    <tableColumn name="Species" id="5"/>
  </tableColumns>
  <tableStyleInfo name="TableStyleLight9" showColumnStripes="0" showRowStripes="1" showLastColumn="0" showFirstColumn="0"/>
</table>
```


``` r
library(dplyr) # only for bind_rows()

library(openxlsx2) # commit acfdffd
file.copy("~/Neuer Ordner/tabnaming.xlsx", ".")
#> [1] TRUE
wb1 <- wb_workbook()
wb1 <- write_xlsx(x = list(head(mtcars), head(iris)), as_table = TRUE)
wb1$remove_tables(sheet = 1, table = "Table1", remove_data = FALSE)
wb1$save("tabnaming_r.xlsx")
wb1 <- wb_load("tabnaming_r.xlsx")
wb2 <- wb_load("tabnaming.xlsx")

bind_rows( xml_attr(wb1$tables$tab_xml, "table"))[c("name", "id")]
#> # A tibble: 1 × 2
#>   name   id   
#>   <chr>  <chr>
#> 1 Table2 2
bind_rows( xml_attr(wb2$tables$tab_xml, "table"))[c("name", "id")]
#> # A tibble: 1 × 2
#>   name     id   
#>   <chr>    <chr>
#> 1 Tabelle2 2

wb1$add_data_table(1, dim = "G1", x = data.frame(a=1,b=2))
wb2$add_data_table(1, dim = "G1", x = data.frame(a=1,b=2))

bind_rows( xml_attr(wb1$tables$tab_xml, "table"))[c("name", "id")]
#> # A tibble: 2 × 2
#>   name   id   
#>   <chr>  <chr>
#> 1 Table2 2    
#> 2 Table2 3
bind_rows( xml_attr(wb2$tables$tab_xml, "table"))[c("name", "id")]
#> # A tibble: 2 × 2
#>   name     id   
#>   <chr>    <chr>
#> 1 Tabelle2 2    
#> 2 Table2   2
```

<sup>Created on 2024-10-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by mlell** [comment]
The fix did work though, re-executing the code in the previous post for commit ´d359f18` does not generate duplicate ids anymore, but uses IDs 2 and 3 in for both input files

**Comment by JanMarvin** [comment]
Thanks for testing!

**Comment by JanMarvin** [comment]
> Thank you for tackling this so quickly! However, the test you provided does not seem to capture the problem. It also passes on the non-patched version.

Thanks for the clarification, I was a little confused at first, but you are obviously right. The test did work previously. Why did it work, because `openxlsx2` does not apply all the tweaks spreadsheet software applies to the internals of a file. When we remove a table, we do not update all references. So after saving and loading the worksheet relationship looks like this:

```R
wb$worksheets_rels
#> [[1]]
#> [1] "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/table\" Target=\"../tables/table2.xml\"/>"
```

Whereas spreadsheet software most likely updated the relationship and the table xml file is now `table1.xml`. Since we previously searched for the max integer of the table file name, in a file that was saved by spreadsheet software, the max id would be 1. And we would write a new table with `id = "2"`. The PR I applied, picks the highest  id from the table xml structure and therefore should not run into this bug. I'm not sure that there's a better test without using external files.

**Comment by JanMarvin** [comment]
This would be a case similar to the broken file

``` r
library(openxlsx2)
wb <- write_xlsx(x = head(Orange), as_table = TRUE)
# we had two tables, the first one is removed and table 1 is now id="2"
wb$tables$tab_xml <- xml_attr_mod(
  wb$tables$tab_xml,
  xml_attributes = c(id = "2")
)
wb$add_data_table(x = head(Orange), dims = "E1:G7")
```
