### ISSUE TITLE
[Feature request] add_named_function

### ISSUE THREAD

**Issue by vorpalvorpal** [JanMarvin/openxlsx2#1157]
Hi,

Excel allows for the creation of named functions. As far as I can tell, in the xml, this is exactly the same as named regions, except instead of the address, a function (with lots of added `xlfn_`). The following seems to work for me.

```{r}
wb_create_named_function <- function(wb, function_name, function_body) {
  xml <- xml_node_create("definedName",
                         xml_children = function_body,
                         xml_attributes = c(name = function_name))
  wb$workbook[["definedNames"]] <- c(wb$workbook[["definedNames"]], xml)
  return(wb)
}

wb <- wb_workbook()$add_worksheet("S1")

wb <- wb_create_named_function(wb, "format_categories", '_xlfn.LAMBDA(_xlpm.val,_xlpm.quant,_xlpm.g, _xlfn.IFS(   ISBLANK(_xlpm.val), "",   AND(NOT(_xlpm.quant), NOT(ISBLANK(_xlpm.quant))), "not quantified",   AND(_xlpm.val &gt;= INDEX(_xlpm.g, 5), NOT(ISBLANK(INDEX(_xlpm.g, 5)))), "guideline 4",   AND(_xlpm.val &gt;= INDEX(_xlpm.g, 4), NOT(ISBLANK(INDEX(_xlpm.g, 4)))), "guideline 3",   AND(_xlpm.val &gt;= INDEX(_xlpm.g, 3), NOT(ISBLANK(INDEX(_xlpm.g, 3)))), "guideline 2",   AND(_xlpm.val &gt;= INDEX(_xlpm.g, 2), NOT(ISBLANK(INDEX(_xlpm.g, 2)))), "guideline 1",   TRUE, ""))')

# Edit: And now a simple formula
wb <- wb_create_named_function(
  wb, 
  "sum_2", 
  '_xlfn.LAMBDA(_xlpm.x, _xlpm.y, _xlpm.x + _xlpm.y)')

wb$open()
```

I am using that crazy big formula, because I couldn't get it to work with `add_formula()` in either openxlsx2 or openxlsx. But by adding the formula as a named formula, I am able to get around this restriction.

So, if you think this is a useful feature, either the existing `wb_add_named_region()` function could be updated to have an additional argument, `function_body` (or something) and require that either `dims` or `function_body` is not missing. Or a whole new function `wb_add_named_function` could be created. Let me know what you think and if you are interested, I'll try putting together a PR.

**Comment by JanMarvin** [comment]
Hi, i can’t say that I fully understand what is going on, but if you can make it work with `wb$add_named_region()` why not? Oh and a shorter formula would be appreciated.

Just fyi: I have been thinking about adding these `_xlfn` and `_xlpm` prefixes, but haven’t figured out how to parse the formulas from the excel webpage.

**Comment by JanMarvin** [comment]
To clarify my previous comment, I'd prefer it, if we could make this work in `wb_add_formula()`. But once we have it working with `wb_add_named_region()` this should be straightforward. Having multiple functions doing the same thing is rather confusing for the user.

**Comment by JanMarvin** [comment]
I guess it’s something like this: https://excel.tv/using-named-formulas-in-excel-like-yesterday/ ?

**Comment by vorpalvorpal** [comment]
Okay, so as far as I can tell the xml (in `xl/workbook.xml`) is as follows:

```xml
<definedNames>
  <definedName name="Sum_2">_xlfn.LAMBDA(_xlpm.x,_xlpm.y, _xlpm.x+_xlpm.y)</definedName> 
  <definedName name="Sum_3">Sheet1!$A$1</definedName>
</definedNames>
```

The first is a named formula and the second is a named range. They are exactly the same, except for the content being either a formula or a cell reference. `wb_add_named_region` currently implements the required name checking for the name attribute. `wb_add_formula` currently implements basic checking for formulas (at the moment, it looks like this is just removing surrounding curly brackets and setting `array = TRUE`, but you suggested that in the future this might involve adding in `_xlfn`/`_xlpm`).

So, if you want it in `wb_add_formula`, I think the following is needed:
- refactor `wb_add_named_region` to take out the name checking code as a new function (`check_xl_name` ?)
- refactor `wb_add_named_region` to take out the bit that actually writes to `wb$workbook[["definedNames"]]` as a new function `write_definedNames()`
- `wb_add_formula` should have an additional argument `name` (or something else?), and logic that requires either `dims` OR `name` to be set.
- `wb_add_formula` should first do what ever formula checking we need, then check if we are writing to a cell or to a name, and if we are writing to a name, call `check_xl_name(name)` followed by `write_definedNames(name, formula)`, otherwise, if `dims` is defined, continue on as normal.

Does this sound reasonable? I'm not really familiar with your codebase, so I have no idea what good function and or argument names are.

**Comment by vorpalvorpal** [comment]
Also, I need to check if there is any recording of an `array` or `cm` attribute in `<definedName>` .

**Comment by JanMarvin** [comment]
Hi @vorpalvorpal , sorry, I realized that I had given you an impossible try. I wanted to avoid randomly adding things to `wb$workbook`, but that's impossible with `wb_add_named_region()`. 

I have added a first PR in #1158. Could you give this a try? This might need some further tweaking, but I have to work now and I'm still not entirely sure that this is what you are looking for :)

Btw, the `cm` related warnings are still there, because I haven't really worked with `cm` formulas and so far nobody has replied that they work as expected with loaded workbooks and in other circumstances ...

``` r
library(openxlsx2)

# wb <- wb_workbook()$add_worksheet()
# wb$add_formula(x = "TODAY() - 1", as_named_region = "YESTERDAY")
# wb$add_formula(x = "=YESTERDAY", dims = "A1", cm = TRUE)

wb <- wb_workbook()$add_worksheet()
wb$add_formula(x = "_xlfn.LAMBDA(TODAY() - 1)", as_named_region = "YESTERDAY")
#> formula registered to the workbook
wb$add_formula(x = "=YESTERDAY()", dims = "A1", cm = TRUE)
#> Warning in write_data2(wb = wb, sheet = sheet, data = x, name = name, colNames
#> = colNames, : modifications with cm formulas are experimental. use at own risk

wb$add_data(x = sample(seq(9), 2), dims = "B2:C2")
wb$add_formula(x = "_xlfn.LAMBDA(_xlpm.x, _xlpm.y, _xlpm.x + _xlpm.y)", as_named_region = "SUM_2")
#> formula registered to the workbook
wb$add_formula(x = "=SUM_2(B2, C2)", dims = "A2", cm = TRUE)
#> Warning in write_data2(wb = wb, sheet = sheet, data = x, name = name, colNames
#> = colNames, : modifications with cm formulas are experimental. use at own risk

if (interactive()) wb$open()
```

As an alternative, we could pass a named character to `wb_add_formula()`, but not sure if this is better:

```R
# Draft code
wb$add_formula(x = c(SUM_2 = "_xlfn.LAMBDA(_xlpm.x, _xlpm.y, _xlpm.x + _xlpm.y)"))
```

**Comment by JanMarvin** [comment]
I have updated the logic, to use named formulas so this should be used in the future:

```R
# Draft code
wb$add_formula(x = c(SUM_2 = "_xlfn.LAMBDA(_xlpm.x, _xlpm.y, _xlpm.x + _xlpm.y)"))
```

I wanted to avoid new additional arguments and didn't want to use the current ones in confusing ways. So `wb_add_formula(x = ..., name = "foo")` creates a named region `foo` and `wb_add_formula(x = c(foo = ...))` creates a named formula `foo` which can be used in the workbook.
