### ISSUE TITLE
`wb_add_data()` errors when `x` contains list columns

### ISSUE THREAD

**Issue by elipousson** [JanMarvin/openxlsx2#1199]
Please correct me if I'm wrong but it looks like the `sep` argument is not implemented. As a result, `wb_add_data()` errors when `x` contains list columns. Here is an example to illustrate the issue:

``` r
library(openxlsx2)

tbl <- tibble::tibble(
  "CharCol" = LETTERS,
  "ListCol" = lapply(
    LETTERS, \(x) {
      sample(LETTERS, replace = TRUE, size = 5)
      }
  )
)

wb_workbook() |> 
  wb_add_worksheet() |> 
  wb_add_data(
    x = tbl
  )
#> Error: Not compatible with STRSXP: [type=list].

packageVersion("openxlsx2")
#> [1] '1.11.0.9000'
```

<sup>Created on 2024-12-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by JanMarvin** [comment]
Thank for the report, @elipousson! Indeed we didn't do anything with the `sep` argument. Could you have a look if the implementation is valid for your case?

If you want something backward compatible, maybe use something like this?
``` r
tbl <- tibble::tibble(
  "CharCol" = LETTERS,
  "ListCol" = lapply(
    LETTERS, \(x) {
      sample(LETTERS, replace = TRUE, size = 5)
    }
  )
)

is_list      <- is.list(tbl)
tbl[is_list] <- lapply(tbl[is_list], function(x) sapply(x, paste, collapse = ", "))

head(tbl)
#> # A tibble: 6 × 2
#>   CharCol ListCol      
#>   <chr>   <chr>        
#> 1 A       G, K, W, M, I
#> 2 B       A, L, N, G, R
#> 3 C       S, W, Y, R, Z
#> 4 D       Z, G, E, R, P
#> 5 E       O, H, E, M, V
#> 6 F       K, B, C, T, Q
```

**Comment by JanMarvin** [comment]
Thanks, merged the PR. 1200 issues, pull requests, discussions and two plus years of development and still this issue some slipped through 😄
