### ISSUE TITLE
Adding an image to header/footer - or at least not overwriting an existing image LEFT while editing RIGHT

### ISSUE THREAD

**Issue by SchmidtPaul** [JanMarvin/openxlsx2#1209]
I currently need to an image to the LEFT header of all my sheets. Am I understanding correctly that this does not work?

- [`wb_add_image()`](https://janmarvin.github.io/openxlsx2/reference/wb_add_image.html) wont do headers and
- [`wb_set_header_footer()`](https://janmarvin.github.io/openxlsx2/reference/wb_set_header_footer.html) wont do images

I actually would not even have to add the image, as it is already present in the template xlsx I am using. However, since I am loading the template via `wb_load()` and must then edit the content of the RIGHT header, it will automatically replace the LEFT header as well. This is confusing to me, because in the docs it says "Use NA to skip a position." but the following code will remove the image in the LEFT header anyway:

```r
wb$set_header_footer(
  sheet = 1,
  header = c(NA, NA, "my_edit")
)
```

**Comment by JanMarvin** [comment]
Hi @SchmidtPaul , this is indeed not supported, but I got something for you. Maybe you get it working: https://github.com/JanMarvin/openxlsx2/discussions/929

Let me know, maybe we can work to implement this

**Comment by JanMarvin** [comment]
Regarding the header ... yeah, sorry. No idea. I have literally zero use for this, hence haven't looked at it ever, other than fixing issues. Therefore, any suggestion/help is appreciated.

**Comment by JanMarvin** [comment]
Hi @SchmidtPaul , could you have a look if #1211 fixes your issue?

**Comment by SchmidtPaul** [comment]
Hi @JanMarvin, thanks for the input. This does work! I simply replace
```r
img <- tempfile(fileext = ".png")
png(img)
barplot(1:10)
dev.off()
wb$add_image(dims = NULL, file = img)
```

with this:
```r
img <- "source/img/image3.png"
wb$add_image(dims = NULL, file = img)
```

for my purposes. However, I can't move it to the left header instead of the right. Apparently, it needs more than just changing this line?

```r
list(oddHeader = c("", "", "&amp;G")) # image on the right
```

**Comment by JanMarvin** [comment]
If you install from the `main` branch (either with r-universe or with `remotes`), you should be able to load the file with `wb_load()`, skip the header part where the image is and modify only the part that you want to alter. This is what you initially wanted? Could you please give this a try?

My snippet above was just toying around with the image functionality, but I haven't spent time to research the actual tweaking how to place or resize the image. This would require creating a few examples and starring at the XML code, and to be honest, I don't have the motivation for this.

**Comment by SchmidtPaul** [comment]
Yes! Thank you!

Now, the following code will indeed leave the left and middle headers as they are in the original file instead of making them empty. In other words, it is the behaviour promised in the documentation: "Use NA to skip a position."

```r
wb <- wb_load(file = my_path)
wb$set_header_footer(sheet = 'mysheet', header = c(NA, NA, 'mytext'))
```

This works for me, as I will simply add the image in the header of the template file stored in `my_path`.

**Comment by JanMarvin** [comment]
Perfect, thanks for testing!
