### ISSUE TITLE
Vignette: Build a simple workbook

### ISSUE THREAD

**Issue by jmbarbone** [JanMarvin/openxlsx2#13]
It would be helpful to start using vignettes for complete tasks (might help keep the examples in the help docs a little simple).  For starters, I think we can have a short, complete example of building/saving a workbook:

- Make some sample data
- Initiate the Workbook
- Add worksheets and data (add to the same sheet ones or twice?)
- Add a simple style
- Save the workbook

**Comment by JanMarvin** [comment]
Closing, guess we have enough examples, but if you want to add one just go for it :)
