### ISSUE TITLE
Review `openxlsx_options()`

### ISSUE THREAD

**Issue by jmbarbone** [JanMarvin/openxlsx2#176]
We have this copied into everything.  I haven't really touched this (keeping code as is for safety) but I think we're too loose with it.

```r
openxlsx_options <- function() {
  # op <- openxlsx_options()
  # on.exit(options(op), add = TRUE)
  options(
    # increase scipen to avoid writing in scientific
    scipen = 200,
    OutDec = ".",
    digits = 22
  )
}
```

I believe these settings are to ensure that when we write numeric data that we aren't losing any accuracy.  We can probably remove it in most cases and retain this somewhere in the write functions.

**Comment by JanMarvin** [comment]
Completely agree. We have previously discussed this in another issue. Afaik all of these can be removed. We only need them when writing data, to avoid scientific notation that would be unknown to openxml. I always assumed that we might want to pass additional options along.
