### ISSUE TITLE
imported xlsm shoud write temp xlsm for wb$open()

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#200]
[macro.xlsm.zip](https://github.com/JanMarvin/openxlsx2/files/8765196/macro.xlsm.zip)

If some xlsm file is loaded it will not open if opened with `wb$open()` due to the file ending being xlsx. If xlsm is imported, if should be written as such. Might simply check if `wb$vbaProject` contains a binary file. (Might also be beneficial, if we ever want to be able to copy bin files from one workbook to another.) Otherwise we would have to store the file ending of the imported workbook.

```R
# get and unzip the file
tmp <- tempdir()
setwd(tmp)
curl::curl_download("https://github.com/JanMarvin/openxlsx2/files/8765196/macro.xlsm.zip", "macro.xlsm.zip")
unzip("macro.xlsm.zip", exdir = ".")

# load and open it
wb <- wb_load("macro.xlsm")
wb$open()
```
<img width="575" alt="Screenshot 2022-05-24 at 20 11 39" src="https://user-images.githubusercontent.com/1645626/170103939-e3541369-2bb1-4616-beee-e642d366da83.png">

**Comment by jmbarbone** [comment]
We can add that `vbaProject` check inside `$open()` and then probably have a separate `temp_xlsm()` function (same as `temp_xlsx()`) for the file path.  It might also be useful to have a check in `$save()` to give a warning when the file extension is `xlsx` but there's a bin file in `vbaProject.

Maybe a `private$macro_enabled` field would be good to simplify the checks.

**Comment by JanMarvin** [comment]
I've pushed a poor mans solution in #202, feel free to improve this :)
