### ISSUE TITLE
High-Level style helpers

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#226]
* [x] `add_border()` #220 (provides only the options I considered helpful)
* [x] `add_fill()` #222
* [x] `add_font()` #228
* [x] `add_numfmt()` #229
* [x] `add_cell_style()` #230 various options, similar to `create_cell_style()`. might replace bare metal functions in previous functions. Might look into cellstyle xf
* [ ] `add_sheet_style()` ( ... maybe?)

This reduces the first example shown here: https://janmarvin.github.io/openxlsx2/articles/openxlsx2_style_manual.html

```R
# all functions need a canvas to draw on
wb <- wb_workbook()$add_worksheet("S1", gridLines = FALSE)$add_data("S1", mtcars)
# add a thick border below the colnames
wb$add_border("S1", dims = "A1:K1", bottom_border = "thick", bottom_color = c(theme = "4"))
# fill the back of the colnames
wb$add_fill("S1", dims = "A1:K1", color = c(theme = "3"))
# change the font of the colnames
wb$add_font("S1", dims = "A1:K1", color = c(theme = "2"), name = "Arial", size = "16")
# add number format
wb$add_numfmt("S1", dims = "A1:A33", numfmt = 2)
# add another number format
wb$add_numfmt("S1", dims = "F1:F33", numfmt = "#.0")
# open the workbook
wb$open()
```

**Comment by JanMarvin** [comment]
Hmm, I plan to work on the remaining functions tomorrow (`add_numfmt()` and a simple `add_cell_style()` for centering, for example). Am a bit tired today, it's been a long week already. After that, we can always talk about improvements. Reducing code is more than welcome and I'd be very happy if you go through this code mess once I'm done. You are a bit better at creating user friendly code :) (and someone needs to add the `wb_wrapper` tests, hehe).

However, I'm not sure why you want this specs code. Maybe I'm missing something, but I don't see any advantages in the design you created. I still want to revive some of the options (afaik there were or are some for frame colors), but otherwise I'm not sure what else these specs would bring.

**Comment by jmbarbone** [comment]
> You are a bit better at creating user friendly code :)

Probably just really picky and good at over-engineering.

> I'm not sure why you want this specs code. 

A few reasons I can think of:
* Move entry validation into separate functions -- moving it outside of the R6 method might make it easier to review -- easier to trace the error codes to the spec building and not distract from other parts of the function.  
* Less parameters to remember for the larger `$add_borders()` and such functions (yes we might have _more_ but it could _feel_ like less)
* Maybe a fun `print` or `plot` method to see what they'd look like? (the combined one, not the individuals)
* Ability to create spec objects and save them for other use.  Good for writing your own custom formats (especially good if you have your company colors)
* Might be more similar to using `ggplot2` and `gt` which contain a lot of fine tuning and have some reliance of similar behaviors.

**Comment by JanMarvin** [comment]
> > You are a bit better at creating user friendly code :)
> 
> Probably just really picky and good at over-engineering.

Don't sell yourself short! :)

> > I'm not sure why you want this specs code.
> 
> A few reasons I can think of:
> 
> * Move entry validation into separate functions -- moving it outside of the R6 method might make it easier to review -- easier to trace the error codes to the spec building and not distract from other parts of the function.
> * Less parameters to remember for the larger `$add_borders()` and such functions (yes we might have _more_ but it could _feel_ like less)
> * Maybe a fun `print` or `plot` method to see what they'd look like? (the combined one, not the individuals)
> * Ability to create spec objects and save them for other use.  Good for writing your own custom formats (especially good if you have your company colors)
> * Might be more similar to using `ggplot2` and `gt` which contain a lot of fine tuning and have some reliance of similar behaviors.

I have given it some thought. I think I like what you have sketched. My initial doubts stemmed from the incredibly long names of the functions, but in the end it looks cleaner and is perhaps easier to understand than my original approach. I'm looking forward to your implementation!
