### ISSUE TITLE
Rgui names deprecated warning 

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#239]
When importing a workbook in Rgui and selecting `wb$sharedStrings` I see a warning that I should use `get_sheet_names`. Not sure if spurious or if we use `names` somewhere in our code.

**Comment by jmbarbone** [comment]
Might be good to double-check the `.libPaths()` and `packageVersion("openxlsx2")` within the Rgui to make sure it's using what you're expecting -- especially if you don't use the Rgui much.

**Comment by JanMarvin** [comment]
Thanks, I don't ever use it indeed. Looks fine. I'll try to check our code later today.

**Comment by JanMarvin** [comment]
possible fix in #240

**Comment by D3SL** [comment]
I think I'm getting this. Trying to use openxlsx2 interactively in VSCode is impossible, and it winds up breaking something in R so badly that every single operation in the console spams a message about openxlsx2.

```R
r$> library(tidyverse)
-- Attaching packages ---------------v ggplot2 3.3.5     v purrr   0.3.4
v tibble  3.1.6     v dplyr   1.0.7
v tidyr   1.1.4     v stringr 1.4.0
v readr   2.1.1     v forcats 0.5.1
-- Conflicts ------------------------x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag() 

r$> library(openxlsx2)

Attaching package: 'openxlsx2'

The following object is masked from 'package:readr':

    write_file


r$>
    bigtest<-wb_workbook()
warning messages from top-level task 
callback 'vsc.workspace'
Warning message:
'names.wbWorkbook' is deprecated.
Use '$get_sheet_names()' instead.
See help("Deprecated") 

r$> 2+2
[1] 4
warning messages from top-level task 
callback 'vsc.workspace'
Warning message:
'names.wbWorkbook' is deprecated.    
Use '$get_sheet_names()' instead.    
See help("Deprecated") 


```

**Comment by JanMarvin** [comment]
Hi @D3SL ,

thanks for the report. That is a bit inconvenient and as a first attempt we should simply drop the depreacted warning on `names.wbWorkbook()`. Obviously either your R console or some `tidyverse` package tries some evaluation in the background, that triggers this warning.

It's not visible in Rstudio nor in R in a console on Linux or Mac where we tested.
