### ISSUE TITLE
custom na.string when writing

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#250]
Right now we allow reading from a file with all types of `na.strings`, but we only write `#N/A` expressions. This is perfectly fine, though we might provide the functionality to create custom `na.strings`. We could capture `NA`s and 
* write `<is><t>na.string</t></is>`
* or do the same but with shared strings (especially helpful if we write many missing cells, we would have to create just one shared string and use `c_t = "s"` and the shared string id when writing `<v>`). This might be something for when we have #67 
* if `na.string = NULL` we could skip adding any value. Therefore the cell would be empty. This is not identical to `na.string = ""` where the cell would contain `<is><t>""</t></is>`

**Comment by AomoDa** [comment]
👍
