### ISSUE TITLE
Unintended whitespace in waiver

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#329]
https://github.com/JanMarvin/openxlsx2/blob/86c910f7da32f087a0c07f67886fd97be56e7238/R/class-workbook.R#L376

This creates "Sheet  1" instead of "Sheet 1". Just for reference Excel uses "Sheet1". In addition this is localized, in German Excel sheets are called "Tabelle" instead of Sheet. If we ever run out of ideas what to do, we could provide something like this too.

**Comment by jmbarbone** [comment]
That should definitely be a `paste0()` or `"Sheet"` instead.

Do we handle any locality differences anywhere else?  I think the original `openxlsx` codebase uses `"Sheet"` everywhere but something like this could include some `switch()` or `getOption()` to adjust.

**Comment by JanMarvin** [comment]
No we don't handle localization anywhere else. In this regard Excel is the worst tool ever. Every Excel function is localized. In a German Excel you would get the sum of two values with: `SUMME(A1:A2)`. In the XML this is still written as `SUM(A1:A2)`. Would be nice to have something like a translator for Excel functions, but realistically that is out of reach and honestly nothing I plan to work on in the foreseeable future. Maybe there is some JavaScript library that does it, or other websites.

With the sheet name that's kinda different. We could localize that, but ofc that has the potential to open another can of worms, because the output would be different based on the R locale.

**Comment by JanMarvin** [comment]
Regarding localization of Excel functions, I've opened a discussion with a list of functions and their german localization scraped from the microsoft support website https://github.com/JanMarvin/openxlsx2/discussions/334 . Just for fun, not gonna work on it further.
