### ISSUE TITLE
copy between workbooks 

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#380]
Currently we only support copying sheets and styles on a single workbook. Ideally we should be able to copy workbooks across workbooks. Though that requires a lot of things we have to think about and to adjust.

We need to collect everything related to a worksheet
* rels
* shared strings
* styles
* pivot tables 
* slicers 
* charts
* drawings 
* etc

We have to merge this with the new workbook and adjust all the references. Shared strings point to new indices. Same for styles. Names for references change. 

Good news: It's definitely doable and a few parts of the clone code should already be useable.
Bad news: It's still a project and most likely not done on a single rainy weekend.

**Comment by olivroy** [comment]
Hi, 

Just had the chance to try this out.

```r
wb <- wb_workbook()$add_worksheet("xxx")
wb2 <- wb_workbook()$add_worksheet("aaa")
wb$clone_worksheet(old = "xxx", from = wb2)
# I would expect this sheet to be named xxx, but it is named next_sheet.
```
Otherwise, seems to work as expected for now. Will try it more after.

**Comment by JanMarvin** [comment]
Thanks, I’ll have a look when I revisit #807
