### ISSUE TITLE
Local named ranges get jumbled

### ISSUE THREAD

**Issue by nicojx** [JanMarvin/openxlsx2#422]
I have no idea what causes this problem: it appeared in a large spreadsheet I was working on and I have not managed to reproduce it:

The scope of a 'local' named range in an Excel workbook changes after being opened and written by openxlsx2. The original scope was sheet "dataSheet", after writing the data using `wb_save()` the scope of the range changed to "Sheet25".

A couple of points:
1. Various things seem to change the result. 
    1. If I delete sheets that are neither the original or the new scope, the jumbling changes (or stops, depending)
    2. If I delete unaffected named ranges, the jumbling changes
    3. If I delete (rather than clear) all data in sheets, including those neither original nor new scope, the jumbling changes
2. I have gone through a process of trying to isolate the problem by removing items from a rather complex original workbook to one that still has the problem but a lot less other things. No data, no macros, fewer named ranges, etc. 
    1. The original had a data connection. In the reduced version I have deleted this (in Excel), but I'm not sure it has properly deleted.
    2. The Excel menu still allows me to show "Properties" (Data > Queries and Connections > Properties), when the sheet that used to have the data connection ("dataSheet") is selected. This is not possible in the version saved by `openxlsx2`
4. I have tried to recreate _exactly_ the same workbook from scratch: same sheets (including internal names), same data, same order, same formatting, same named ranges -- the problem does not appear.
    1. I have copied the table (only the header row) where the data connection used to be. This also enabled the "Properties" dialog, but also didn't reproduce the probem.

I'm attaching four spreadsheets:
1. The problematic original -- before opening / saving with `openxlsx2`
3. The problematic original -- after opening / saving with `openxlsx2`
4. The self-created copy -- before
6. The self-created copy -- after

[XLS-nomac-noconn-anon-42.xlsx](https://github.com/JanMarvin/openxlsx2/files/10044802/XLS-nomac-noconn-anon-42.xlsx)
[XLS-nomac-noconn-anon-42-oxlsx2-419.xlsx](https://github.com/JanMarvin/openxlsx2/files/10044803/XLS-nomac-noconn-anon-42-oxlsx2-419.xlsx)
[recreate.xlsx](https://github.com/JanMarvin/openxlsx2/files/10044800/recreate.xlsx)
[recreate-01-oxlsx2-419.xlsx](https://github.com/JanMarvin/openxlsx2/files/10044801/recreate-01-oxlsx2-419.xlsx)

I hope this provides some help in isolating (and fixing) the problem, I'm stuck.

Btw., I used pull request version #419 to test this.

**Comment by JanMarvin** [comment]
Hi @nicojx ,

thanks for the detailed report. I was able to spot the faulty code here. Not sure what it does, but if I comment these lines, the named region is unaltered. I pushed a commit to remove this code chunk. You could try to rebuild #419 and see if the issue is resolved.

https://github.com/JanMarvin/openxlsx2/blob/48d69f95a3dae5d015a2a41338ee13cc4fe3fbe0/R/class-workbook.R#L6047-L6069

**Comment by nicojx** [comment]
Amazing, problem solved. Thanks a lot!
