### ISSUE TITLE
wb_add_data(..., na.string = NULL) does not work with NA_character_ 

### ISSUE THREAD

**Issue by nicojx** [JanMarvin/openxlsx2#429]
Hopefully my last one.. I have nearly everything working :)

When writing a character NA (`NA_character_`) using the option `wb_add_data(..., na.strings = NULL)`, the cell is not left blank, but instead `_openxlsx_NA` is written in the cell.

```R
wb_workbook()$
  add_worksheet("Sheet1")$
  add_data(
    dims = "A1",
    x = NA,
    na.strings = NULL
  )$
  add_data(
    dims = "A2",
    x = NA_character_,
    na.strings = NULL
  )$
  open()
```

**Comment by JanMarvin** [comment]
PR in #430. Thanks again! For the time being you can use `na.strings = ""`. The effect on the user side will be the same. 
* `NULL` erases the cell entirely in XML we write: `<c r="A1"/>`. The cell has no content. 
* With `na.strings = ""` we will write: `<c r="A1"><is><t></t></is></c>`. 

The effect will be the same, just that the file will be a little larger in the second case (and Excel will know that the current cell content is of type character).

**Comment by nicojx** [comment]
Amazing, thanks for your quick responses! :)
