### ISSUE TITLE
Ampersands ("&") are read as "&amp;"  

### ISSUE THREAD

**Issue by nicojx** [JanMarvin/openxlsx2#435]
Reading data containing ampersands ("&") results in the ampersand being read as "&amp;". This only seems to happen when the file is read from disk. Might also affect other special characters.

```R
library(openxlsx2)
wb <- wb_workbook()$add_worksheet("Test")$add_data(dims = "A1", x = "A & B")$save("ampersand.xlsx")
read_xlsx(wb, sheet = "Test")
# A & B
read_xlsx("ampersand.xlsx", sheet = "Test")
# A &amp; B
```

**Comment by JanMarvin** [comment]
Thanks for the report! Fixed in #436 If the CI is green, I'll merge it straight away.
