### ISSUE TITLE
consider raising the version of R in Depends section of package DESCRIPTION

### ISSUE THREAD

**Issue by jlacko** [JanMarvin/openxlsx2#568]
Dear openxlsx2 devs:

first of all thanks for a great package! It helps me immensely in my daily work.

Secondly: consider raising the required version of R in DESCRIPTION; it currently reads as R (>= 3.4.0)

This feels not quite correct, given that the package uses function `...names()` which only comes from R 4.1.0

https://github.com/JanMarvin/openxlsx2/blob/50a4248adf4343a76cc4696fc42bd623fd2e4808/R/class-color.R#L52

It may be a good idea to raise the required R version in some of the future releases (R 3.4.0 is quite ancient by now, and even 4.1.0 feels a bit dated).

Thanks for your consideration!

**Comment by JanMarvin** [comment]
Hi @jlacko , thanks for the hint. We'll see that we can replace `..names()`. Unfortunately in many organisations rollout of new R releases can be daring slow, so without a special reason I don't want to raise the R dependency.
