### ISSUE TITLE
rework `genBaseCore()`, `wbWorkbook` creators and dates

### ISSUE THREAD

**Issue by jmbarbone** [JanMarvin/openxlsx2#57]
Related to this SO issue: https://stackoverflow.com/questions/70926250/can-i-write-identical-xlsx-files-from-the-same-data-frame-in-r/70927972

We can have a field in the `wbWorkbook` object that has the current date creation that users can modify this value.  I don't see the harm in letting a user define this.  It's automatically assumed to be the current time when `genBaseCore()` is called when the workbook object is initialized.

`genBaseCore()` creates `wbWorkbook$core` which is used in:
* `wbWorkbook$addCreator()` --> store a character vector
* `wbWorkbooks$getCreators()` --> simply retrieve character vector
* `wbWorkbooks$changeLastModifiedBy()` --> stores as POSIX
* and lastly `wbWorkbook$saveWorkbook()` --> only one that needs to be 

## Changes

- [ ] move `genBaseCore()` to private method in `wbWorkbook`
- [ ] store creators, modified/created dates as character/POSIXt vector
- [ ] simplify adding/updating functions for the above
- [ ] call `private$genBaseCore()`in `wbWorkbook$saveWorkbook()`
- [ ] add more "core" fields
  - [ ] company
  - [ ] template (would this require any additional linking?)
  - [ ] manager

**Comment by olivroy** [comment]
is this fixed by #782?

**Comment by JanMarvin** [comment]
Ah yes, thanks
