### ISSUE TITLE
Failure with dev waldo

### ISSUE THREAD

**Issue by hadley** [JanMarvin/openxlsx2#584]
I see:

```
── Failure (test-wb_functions.R:83:3): wb_to_df ────────────────────────────────
`test` (`actual`) not equal to `got` (`expected`).

actual vs expected
                   Var3
  actual[1, ]      1.00
- actual[2, ]        NA
+ expected[2, ]     NaN
  actual[3, ]      1.34
  actual[4, ]        NA
  actual[5, ]      1.56

  `actual[[2]][1:5]`: 1  NA 1 NA 2
`expected[[2]][1:5]`: 1 NaN 1 NA 2
```

because waldo now correctly distinguishes between `NA` and `NaN`. I didn't see an obvious way to fix the test (since you seem to be comparing the result to reference data) so this may reveal a genuine bug.

**Comment by JanMarvin** [comment]
Thanks, we convert `"#NUM"` to `NA_real_` which worked previously, now have to look for another way. 

https://github.com/JanMarvin/openxlsx2/blob/14f9696888b0bda1611ec5d77824a2d88316661a/tests/testthat/test-wb_functions.R#L82
Something like this should do the trick 
`..., function (x) as.numeric(replace (x, x == "NUM!", "NaN")))`

**Comment by JanMarvin** [comment]
Should be fixed now in `main`.
