### ISSUE TITLE
[write_xlsx] check arguments

### ISSUE THREAD

**Issue by thornend** [JanMarvin/openxlsx2#598]
The optional parameter na.string in write_xlsx does not appear to work.  I have tried a few options but cells with NA still write as the Excel missing value #N/A.  Reprex:

```
library(openxlsx2)
df1 <- iris[1:5, ]
df1[2:3, 3] <- NA
write_xlsx(df1, "TestIrisNA.xlsx")
write_xlsx(df1, "TestIrisNA2.xlsx", na.string = "")
write_xlsx(df1, "TestIrisNA3.xlsx", na.string = "Anything?")
```

**Comment by JanMarvin** [comment]
Hi @thornend , we have fixed this in the 0.6 release of openxlsx2 afaik #552 . In earlier releases this was indeed broken. Could you please check this with a recent release?

**Comment by thornend** [comment]
Sorry, should have included the version number.  I am using openxlsx2 version 0.6.1 with R 4.1.1 on Windows Server 2019.  I also tested a fresh install of 0.6.1 on my laptop with R 4.2.1.   On both PCs  the code above gives the following output for all three files in Excel for Microsoft 365 MSO 
![Screenshot 2023-05-03 204310](https://user-images.githubusercontent.com/24508632/236029034-bc43e5e5-b691-4452-b695-d73d0b92dbcd.jpg)

**Comment by JanMarvin** [comment]
Oh it's `na.strings` . Could you check that?

**Comment by thornend** [comment]
Ah!  That works.  It is just the help file that needs changing, which should be a lot easier!  I am slightly surprised not to get an "unused argument" error with na.string, or at least a warning?

**Comment by JanMarvin** [comment]
Glad it works! You get now warning, because of the blessing and curse that `...` brings. This basically allows passing of all possible arguments even ones the developers did not define in the first place. `write_xlsx()` accepts many arguments and we or at least I didn't want to list all. We probably should check against some arguments and at least correct the documentation.
