### ISSUE TITLE
Review/update `@examples`

### ISSUE THREAD

**Issue by jmbarbone** [JanMarvin/openxlsx2#61]
I haven't been paying much attention to these, just making some small changes so they don't fail, so I'm not sure if they'll need a refreshing with many of the changes.  We may be able to extract some examples into vignettes that provide a bit more detail into specifications and allow those to exist with more description and care.

Further, we might want to promote accessing objects directly rather than using the wrappers.

Other than that, there are a few instances that we can move (parts of) examples into testing.

**Comment by olivroy** [comment]
For ref, I removed a lot of the old examples in #769 if we ever need them elsewhere.

**Comment by JanMarvin** [comment]
Thanks, closing this.
