### ISSUE TITLE
Problem with cyrillic text

### ISSUE THREAD

**Issue by lz1nwm** [JanMarvin/openxlsx2#640]
This is my example:
```r
library(openxlsx2)
wb <- wb_workbook()
wb$add_worksheet("sheet")
wb$add_data("sheet", 'абвгд')
if (interactive()) wb$open()
```
And I get this message:

![openxlsx2](https://github.com/JanMarvin/openxlsx2/assets/10129222/9deabd92-33ce-433d-b4ea-cbb1ea6a9040)

I am using`openxlsx = 0.7` and I dont have such issue with `openxlsx = 4.2.5.2` .

**Comment by JanMarvin** [comment]
I'll look into this, but it works just fine on my German locale Windows and latin1 R 4.1 and I'm unaware why it should fail in later R releases. Could you please provide some details regarding your setup?

**Comment by lz1nwm** [comment]
```r
- Session info ---------------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 4.3.0 (2023-04-21 ucrt)
 os       Windows 7 x64 
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.1251
 ctype    English_United States.1251
 date     2023-06-07
 rstudio  2023.03.0+386 Cherry Blossom (desktop)
 pandoc   NA

- Packages -------------------------------------------------------------------------------------------------------------------------
 package     * version date (UTC) lib source
 openxlsx2   * 0.7     2023-05-26 [1] CRAN (R 4.3.0)
```

**Comment by lz1nwm** [comment]
Yes it works with numbers and latin letters. And this is the log file listing repairs:

![image](https://github.com/JanMarvin/openxlsx2/assets/10129222/0138c83f-5d71-4996-be79-89c8fb78fb9f)

**Comment by JanMarvin** [comment]
Thanks, looks strange, at least your file looks like it's Unicode, but somehow `אבגדה` and not the Cyrillic text you wrote. Could you please check if the behavior is the same without rstudio? Just R in the console or Rgui? But I'm already at the guesswork stage.

**Comment by lz1nwm** [comment]
Well, it seems the same:
![image](https://github.com/JanMarvin/openxlsx2/assets/10129222/338cdb6a-8e42-4509-a377-3682c1bdf67f)

**Comment by lz1nwm** [comment]
The warning message is:

> During startup - Warning message:
Using locale code page other than 1251 may cause problems. 
But I don't think that it is an issue as as I said `openxlsx` works without any problems with the same operations.

Here is the xlsx file, just remove txt:
[temp_xlsx_2d247657b3.xlsx.txt](https://github.com/JanMarvin/openxlsx2/files/11678822/temp_xlsx_2d247657b3.xlsx.txt)

**Comment by JanMarvin** [comment]
Thanks for the file. `openxlsx` and `openxlsx2` do not really have a shared codebase anymore. Since the fork pretty much everything was rewritten and I don't have access to non unicode Windows anymore. But maybe we're lucky.

**Comment by JanMarvin** [comment]
I'm still trying to wrap my head around what is going on. Apparently the file is written with cyrillic CP1251 encoding. Although that should not have happened (and I was under the impression that `pugi::encoding_utf8`,  would have provided the required unicode conversion), but with encodings you never know. All my usual tests were with R in unicode/latin1 on a unicode filesystem, but your filesystem is obviously not unicode. Therefore it might be required to convert to Unicode. The linked pull request is a first attempt to see what works.

First lets try the following with the CRAN version:
```R
library(openxlsx2)
wb <- wb_workbook()
wb$add_worksheet("sheet")
wb$add_data("sheet", x = iconv('абвгд', to = "UTF-8"))
if (interactive()) wb$open()
```

And second, could you try `remotes::install_github("JanMarvin/openxlsx2#641")` and see if this file is readable?

**Comment by JanMarvin** [comment]
<img width="321" alt="Screenshot 2023-06-07 at 18 51 25" src="https://github.com/JanMarvin/openxlsx2/assets/1645626/f6e05dc6-2e82-41bc-a271-d10bc850ed10">

It works on Mac (R 4.3 and en_US.UTF-8).

**Comment by lz1nwm** [comment]
Both the first and the second solutions work. Thanks! I really appreciate your support!

Perhaps I should start a new thread, but I would like to ask why `wb$add_worksheet("sheet")` is not the same as `wb_add_worksheet(wb, sheet = "sheet")`. The latter doesn't actually add a sheet to the workbook. Is this a bug or intentional?

**Comment by JanMarvin** [comment]
Hooray! But now I'm a bit in the mix. Great that the `iconv()` approach works and I'm somehow inclined to simply stick with it, but I have added a second commit that overall might be cleaner. With the simple `iconv()` approach you are able to write from your locale, but you are unable to interact with other files (like `sharedStrings` and probably locales used in the file path). I have updated the pull request and added options to (i) force utf8 encoding and (ii) to add a native locale, we could probably set the current one per default.

Regarding your second question: `wb_add_worksheet()` is a wrapper function that is not supposed to alter the workbook input. If you want to add a sheet with the wrapper function, you have to assign the output. We have some examples and explanation in our vignettes. If you have general questions regarding `openxlsx2` please use the discussion area of this Github repository.

``` r
library(openxlsx2)
wb <- wb_workbook()
# the chained function
wb$add_worksheet("sheet1")
# the wrapper function
wb <- wb_add_worksheet(wb, "sheet2")
```

**Comment by lz1nwm** [comment]
Now that I tested the latest  fix ( 21be7df ) and it fails again. But maybe it is because I should set up some options which I couldn't figure out how to do.

**Comment by JanMarvin** [comment]
Ah sorry, I'm still trying to get it working. Unfortunately it is quite tricky to test something like this without access (and I want to avoid messing on my systems with the locale settings). The idea is, if the following two options are set, the conversion should happen on the fly. Unfortunately there is still something broken.

```R
options("openxlsx2.force_utf8_encoding" = TRUE)
options("openxlsx2.native_encoding" = "CP1251")

library(openxlsx2)
wb <- wb_workbook()
wb$add_worksheet("sheet")
wb$add_data("sheet", 'абвгд')
if (interactive()) wb$open()
```

**Comment by lz1nwm** [comment]
Ok. I tried these options and I could confirm that it works now...

**Comment by JanMarvin** [comment]
Thanks! Still I'd like to have a working test for this ...

**Comment by JanMarvin** [comment]
@lz1nwm could you please check if the following works too?

```R
options("openxlsx2.force_utf8_encoding" = TRUE)
options("openxlsx2.native_encoding" = "CP1251")

library(openxlsx2)

temp <- temp_xlsx()

wb <- wb_workbook()
wb$add_worksheet("sheet")
wb$add_data("sheet", 'абвгд')
# save it
wb$save(temp)
# reload it
wb <- wb_load(temp)
if (interactive()) wb$open()
```

In our R 4.1 Windows latin1 test the imported file looks like this: 
```R
wb$worksheets[[1]]$sheet_data$cc$is[1]
#> "<is><t><U+0430><U+0431><U+0432><U+0433><U+0434></t></is>"
```

which can be converted to UTF-8 using something like `stringi::stri_unescape_unicode(gsub("<U\\+(....)>", "\\\\u\\1", x))`, but I'm interested if this happens at all or if this is just something happening in due to the codepage missmatch.

**Comment by lz1nwm** [comment]
I think that there is a problem with R console.
If I run it in RStudio I get what is expected:
```r
[1] "<is><t>абвгд</t></is>"
```

If I run it in Rgui I get this:
```r
 "<is><t><U+0420>°<U+0421><U+0403><U+0420><U+0491><U+0421><U+0403></t></is>"
```
I saved the files using RStudio and it is encoded in `UTF-8`, while the files saved with Rgui is encoded in `Windows-1255`. This is quite strange because I don't write Hebrew at all.

![image](https://github.com/JanMarvin/openxlsx2/assets/10129222/a1bc8814-efef-465b-845f-919704e0a8aa)
![image](https://github.com/JanMarvin/openxlsx2/assets/10129222/77ff1db7-0bc1-4953-a978-9e3b55ce5fd1)

If I try to open the file saved with RStudio in Rgui it shows:
```r
wb$add_data("sheet", '?°?±??????')
```
Then in Rgui I opened the script saved with Rgui and added the line below and it worked:
```r
Sys.setlocale("LC_CTYPE", "Bulgarian") 
```

**Comment by JanMarvin** [comment]
Unfortunately Rstudio interacting with R locales is something I'm quite familiar with. My work environment has a well documented - and equally long fixed - bug where Rstudio modifies all special characters in file strings like the German umlauts `ÄäÖoÜuß` or French accents. Due to some strange interaction they are interpreted completely broken.  On import and export. That's why I asked for the Rgui test in the first place.

Could you please check, if it's possible for you to load and open an XLSX input with Cyrillic characters? If yes, we can merge as is. It's not a complete fix, but fortunately one that should affect less and less users every day.

**Comment by JanMarvin** [comment]
Oh and cp1251 seems to be tricky to identify from just a few characters. `stringi::stri_detect_enc()` is unable to identify the string encoding. That's probably why the encoding is switched to cp1255

**Comment by lz1nwm** [comment]
> Oh and cp1251 seems to be tricky to identify from just a few characters. `stringi::stri_detect_enc()` is unable to identify the string encoding. That's probably why the encoding is switched to cp1255

You are right, if it is a longer string it is detected as 1251.

I did some testing with loading and saving files with Cyrillic characters and then adding sheets with additional Cyrillic characters. The result is that if I use your options the characters in the file are encoded wrongly while the newly added are fine. So finaly wat worked was to set this:
```r
options("openxlsx2.native_encoding" = NULL)
```

**Comment by lz1nwm** [comment]
And this setup worked for RGui as well. 
Also, I used this longer string "абвгдежзийклмнопрстуфхцчшщъьюя".

**Comment by JanMarvin** [comment]
Thank you for testing! I have no clue at all what that string means, but hopefully nothing offensive 😄 
One thing remains, I assume that `wb_to_df()` returns utf8 code. Probably the encoding option could be added there as well.

**Comment by lz1nwm** [comment]
😁 well, these are all Cyrillic letters in alphabetical order, so you can use the string for the test if you need to.... 

Surprisingly, `wb_to_df()` works like a charm without any options. 😲

**Comment by JanMarvin** [comment]
Interesting that `wb_to_df()` works out of the box. Makes me wonder if there's just some missing `Rcpp::String` somewhere in the code.

**Comment by JanMarvin** [comment]
Thanks, I've merged what was in the PR. The conversion part is embedded in the options, therefore it should cause no harm to others. I tried with `Rcpp::String()` in `wide_to_long()`, but that was unsuccessful and while I like to support as many options as possible, the entire encoding part is not really something I like. Hopefully R is long forgotten, when UTF-16/UTF-32 etc. will cause issues :smiley:

**Comment by lz1nwm** [comment]
@JanMarvin what you did is quite enough for my case, thank a lot!
With this fix and the support experience :clap: I'm moving all my scripts to `openxlsx2`.

**Comment by JanMarvin** [comment]
Thanks for the kind words :hugs:  Maybe you can keep a backup, after all `openxlsx` is not going away :wink: But yes, I switched my production scripts to `openxlsx2` a while ago (sometimes that's the only way to catch errors, unfortunately, but there are a lot of them in `openxlsx` and I know that because I might have been the one who wrote them).

There is a vignette that covers a few of the things to watch out for when switching from `openxlsx` to `openxlsx2`, but of course [issues](https://github.com/JanMarvin/openxlsx2/issues) and [discussions](https://github.com/JanMarvin/openxlsx2/discussions) are always just a click away!
