### ISSUE TITLE
wb_load conditional formatting range bug

### ISSUE THREAD

**Issue by Michiel91** [JanMarvin/openxlsx2#646]
I ran into a bug when loading an existing Excel workbook with conditional formatting. The original range of the conditional formatting is incorrectly imported (and therefore also exported). It somehow seems that openxlsx2 appends increasing numbers to the range of the conditional formatting, erroneously modifying it.

Below is an example to reproduce this bug:

1) Create a new workbook in Excel
2) Fill A1:B5 with values 0, 1 and 2.
3) Create new conditional formatting rules for A1:B5. For example bg fill #FFC000 for 0, #92D050 for 1 and #00B0F0 for 2.
4) Load this workbook into R using openxlsx2::wb_load
5) In worksheets[[1]]$conditionalFormatting the three conditional formatting ranges A1:B5 are modified to c('A1:B51', 'A1:B52', 'A1:B53')
6) When exporting the workbook or working with it downstream the conditional formatting rules are now erroneously applied to A1:B51, A1:B52, etc.

Thanks in advance for looking into this unexpected behavior. Let me know if I can help by providing additional examples or information.

**Comment by JanMarvin** [comment]
Hi @Michiel91 , thanks for the report. I can reproduce the exact behavior with the following file:
[cf.xlsx](https://github.com/JanMarvin/openxlsx2/files/11721017/cf.xlsx). I look into it.

**Comment by JanMarvin** [comment]
I've pushed a pull request in #647 . You could check if this solves your issue. I'll add a test and a NEWS entry later. Lunch break is ending :)

**Comment by JanMarvin** [comment]
apparently the fix broke something else. have to check later

**Comment by Michiel91** [comment]
Thanks a lot for already looking into this so quickly! I'll wait for the final fix and will test it once available. Even dedicating your lunch break to fixing bugs is what they call dedication, I hope you still had lunch :).

**Comment by Michiel91** [comment]
Thanks for the fix @JanMarvin, I just tested with the latest development version and can confirm this issue is now solved.
