### ISSUE TITLE
wb_add_conditional_formatting dims argument broken

### ISSUE THREAD

**Issue by Michiel91** [JanMarvin/openxlsx2#654]
When trying the wb_add_conditional_formatting function I noticed that the dims argument is broken. When supplying any (valid) dimension, the following error is returned:
`Error in if (!all(vapply(cellCoords, is_integer_ish, NA))) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In min(rows) : no non-missing arguments to min; returning Inf
2: In min(cols) : no non-missing arguments to min; returning Inf`

Checking the function code, I see that the dims argument is not passed to the underlying add_conditional_formatting function.

The rows and cols arguments work, but they trigger a warning when supplying a previously generated index range. For example when creating a variable called my_cols <- 1:6 and supplying this to the cols argument, the following is shown:
`Warning message:
In wb$clone()$add_conditional_formatting(sheet = sheet, cols = cols,  :
  cols > 2, will create range from min to max.`

Thanks for looking into this.

**Comment by JanMarvin** [comment]
@Michiel91 please provide a minimal reproduce able example. Dims for conditional examples were introduced just recently.

**Comment by JanMarvin** [comment]
This should work: https://github.com/JanMarvin/openxlsx2/pull/645

**Comment by Michiel91** [comment]
Hi @JanMarvin,

As pointed out it should be obvious from the code of wb_add_conditional_formatting that the dims argument is not used anywhere in the function (not passed to the underlying add_conditional_formatting function). Nevertheless hereby a minimum reproduceable example to mimic the error and warning I described:

`# Create example matrix
data <- matrix(sample(0:10, 5), 5, 4)

# Create wb and write example data
wb <- openxlsx2::wb_workbook() %>%
	openxlsx2::wb_add_worksheet("test") %>%
	openxlsx2::wb_add_data(x = data, 
												 sheet = "test")

# Triggers error: Apply conditional formatting using dims
wb %<>%
	openxlsx2::wb_add_conditional_formatting(sheet = "test",
																					 dims = "A1:B5",
																					 type = "between",
																					 rule = c(2, 4))
# Triggers warning: Apply conditional formatting using predefined row and col range
row_range <- 1:5
col_range <- 1:4

wb %<>%
	openxlsx2::wb_add_conditional_formatting(sheet = "test",
																					 rows = row_range,
																					 cols = col_range,
																					 type = "between",
																					 rule = c(2, 4))`

**Comment by JanMarvin** [comment]
Thanks, for the example, I created a pull request to fix this. It's quite warm in my attic apartment and this saved me searching what exactly is the problem in that case. You were completely right and this should be fixed right away.

**Comment by JanMarvin** [comment]
The fix is now in main

**Comment by Michiel91** [comment]
Thanks for the fix @JanMarvin!
