### ISSUE TITLE
wb_set_sheet_names() does not update references

### ISSUE THREAD

**Issue by DavZim** [JanMarvin/openxlsx2#656]
When I rename a sheet in Excel, all the references to it are updated as well.
For example on sheet "base" I have a reference to a cell on sheet "data1" `=data1!A1` or to a named region `=data1!NAMED`.
When I manually rename the sheet to "otherdata" the values get updated to `=otherdata!A1` and `=otherdata!NAMED`.

openxlsx2 only renames the sheets but does not update the references. Eg it would still be `=data1!A1` and `=data1!NAMED`, which results in a `#REF` in both cases but the named region even turns into `='rename-showcase-out.xlsx'!NAMED`.

I have attached two files that showcase that.
The accompanying code is this:

```R
library(openxlsx2)
packageVersion("openxlsx2")
#> [1] ‘0.7’
file <- "rename-showcase.xlsx"
wb <- wb_load(file)
wb <- wb_set_sheet_names(wb, 2, "otherdata")
openxlsx2::wb_save(wb, "rename-showcase-out.xlsx", overwrite = TRUE)
```

this is how the formulas should and actually look like.
![image](https://github.com/JanMarvin/openxlsx2/assets/15910496/d1b2591e-46ce-4fda-b2f4-a9583a6e0abe)

[rename-showcase-out.xlsx](https://github.com/JanMarvin/openxlsx2/files/11830683/rename-showcase-out.xlsx)
[rename-showcase.xlsx](https://github.com/JanMarvin/openxlsx2/files/11830685/rename-showcase.xlsx)

**Comment by DavZim** [comment]
Also, to piggybank on this issue, `wb_set_sheet_names()` does not work with old being a name:
```R
wb <- wb_set_sheet_names(wb, "data1", "otherdata")
#> Error in stringi::stri_replace_all(nn, "'+", "'") : 
#>  you have to specify either `regex`, `fixed`, `coll`, or `charclass`
```

**Comment by JanMarvin** [comment]
Yeah, unfortunately that's never going to be implemented. You have to use spreadsheet software if you want this. References are everywhere, in formulas, named cells, drawings, charts, pivot tables and maybe other workbooks as well. This is also why I won't add a remove columns or rows function. `openxlsx2` has limits and this is one. I can add a note to the description, but I won't work on a fix.

**Comment by JanMarvin** [comment]
I added a note. If you know where the references are, you can still try to modify the cell or xml part to change the reference there as well, but for something like this, I would recommend just saving the file and making the desired/needed changes in spreadsheet software. Afaik we have a similar problem with cloning, where everything is just copied from one spreadsheet to another and all references are kept. You could try to work on this, but let's just say there are reasons why no one has done this yet.

**Comment by DavZim** [comment]
Thanks for the comment.
My use-case required to rename references in formulas and named regions. For this case I wrote and use this function, which might help other users.

```R

wb_rename_sheets2 <- function(wb, old, new) {
  old_id <- unname(which(wb$get_sheet_names() == old))
  
  # may be surrounded by ' if contains spaces
  old_sheet_regex <- paste0("'?", old, "'?!")
  new_name <- new
  if (grepl(" ", new)) new <- paste0("'", new, "'")
  new_sheet_regex <- paste0(new, "!")
  
  # fix named regions
  wb$workbook$definedNames <- gsub(
    old_sheet_regex,
    new_sheet_regex,
    wb$workbook$definedNames
  )
  
  # update formulas in the sheets
  # TODO this will also update text in formulas that matches the names + '!'
  wb$worksheets <- lapply(wb$worksheets, function(w) {
    w$sheet_data$cc$f <- gsub(
      old_sheet_regex,
      new_sheet_regex,
      w$sheet_data$cc$f
    )
    w 
  })
  
  # important to do this last, otherwise the named region is wrong...
  wb <- do.call(openxlsx2::wb_set_sheet_names,
                list(wb = wb, old = old_id, new = new_name))
  
  wb
}
```

**Comment by JanMarvin** [comment]
Wonderful, you might want to pass old and new sheet name through `openxlsx2:::replace_legal_chars("A & B")`.

**Comment by JanMarvin** [comment]
The second formula in cell `B3` is basically a hyperlink into the other workbook. Since this workbook does not contain any worksheet `data1` it is not updated. But this is precisely why I'm hesitant to add reference changes. I'll think about it, on some other day. For now you have something working and know what to look for.
