### ISSUE TITLE
Cloned worksheet with note throws error on wb_save

### ISSUE THREAD

**Issue by DavZim** [JanMarvin/openxlsx2#658]
I have a worksheet with a note (not comment).
When I clone the worksheet, the `wb_save()` command throws an error.

![image](https://github.com/JanMarvin/openxlsx2/assets/15910496/ba92268b-9bf1-4ddc-8637-6016d51a3402)

I use this test-file [test.xlsx](https://github.com/JanMarvin/openxlsx2/files/11833189/test.xlsx).

```R
library(openxlsx2)
wb <- wb_load("https://github.com/JanMarvin/openxlsx2/files/11833189/test.xlsx")
wb$clone_worksheet(1, "ASD")
wb$save("test2.xlsx")
#> Error in FUN(X[[i]], ...) : subscript out of bounds
traceback()
#> 5: lapply(X = X, FUN = FUN, ...)
#> 4: sapply(comment_list, "[[", "author")
#> 3: unique(sapply(comment_list, "[[", "author"))
#> 2: write_comment_xml(comment_list = self$comments[[i]], file_name = file.path(tmpDir, 
#>        "xl", fn))
#> 1: wb$save("test2.xlsx")
```

**Comment by JanMarvin** [comment]
Thanks (once again) for reporting! A fix is in main.

**Comment by DavZim** [comment]
Thank you for the quick fixes! <3
