### ISSUE TITLE
Remove trailing empty rows when wb_read()

### ISSUE THREAD

**Issue by nicojx** [JanMarvin/openxlsx2#675]
Unlike openxlsx's read.xlsx, openxlsx2's `wb_read()` (and likely other read functions) include trailing empty rows by using a different way of determining the size of the area to be read. It would make more sense to exclude those rows (I can't think of any reason someone might be interested in them).

Note this is different from keeping empty rows using `skipEmptyRows`, which are above the last bit of data.

**Comment by JanMarvin** [comment]
Hi @nicojx, thanks for the suggestion. I assume something like a complete cases solution should be possible. Though that would be another argument for a function with already many arguments. My first impression would be I'd be that the user should do the clean up. After all similar things can happen in all external files.

I'll give it some moments to think about.

**Comment by nicojx** [comment]
Thanks @JanMarvin. The main issue is that it can make NAs appear where you don't expect them (because you only have a list of values)--though you're right, that might just be a job for the user.

**Comment by nicojx** [comment]
And I guess what I'm suggesting is that this doesn't need an option (agreed you want to limit those), but to just return limit the area returned to the area that contains data (including empty rows above the last data entry). You already exclude empty rows that beyond the area defined by Excel, i.e. you don't return the max ~1,000,000 rows Excel handles.

**Comment by JanMarvin** [comment]
I understand, but unfortunately that's exactly why I'm thinking about an argument. Otherwise we would create the same inconsistent returns `openxlsx` creates. Sometimes every column and sometimes only a filled range.

From a software point, theses cells are not empty. They exist in the worksheet and in general the user should remove these or restrict the selection to a different cell range. How else should one return empty rows?

**Comment by nicojx** [comment]
I see your point. I guess for most users the way Excel defines a data area is rather arbitrary. As soon as you put data into a cell the data area is expanded to include that cell, and not retracted if you then clear the cell. I definitely agree that empty rows above the last value need to be returned (unless excluded via option), but wasn't sure about the benefit of returning those below the last value (or by extension, the columns to the right of the right-most value). But I take your consistency point, makes sense--happy to close this.

**Comment by JanMarvin** [comment]
Below I have created an example of the problem as far as I understand you. A file with initialized empty cells that are under some normal, meaningfully filled cells.

I remove the empty cells with a three-line function (there is probably a nicer way to do this). Since `wb_to_df()` can return `dims` and named regions, we can't reduce the data by default. Not every named region is filled and not all selected cells are filled either.

If I understand correctly and if you can solve the issue this way, I would like to close this issue. Otherwise we could add a new argument that will basically call something like this function internally.

``` r
library(openxlsx2)

# create a workbook with a few lines of data and empty initialized cells
wb <- wb_workbook()$add_worksheet()$
  # add meaningful data
  add_data(x = head(iris))$
  # more meaningful data
  add_data(dims = "A9", x = tail(iris, 2), colNames = FALSE)$
  # add empty cells
  add_data(dims = "A11", x = matrix(NA, 5, 5),
           na.strings = NULL, colNames = FALSE)

df <- wb_to_df(wb)
df
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
#> 2           5.1         3.5          1.4         0.2    setosa
#> 3           4.9         3.0          1.4         0.2    setosa
#> 4           4.7         3.2          1.3         0.2    setosa
#> 5           4.6         3.1          1.5         0.2    setosa
#> 6           5.0         3.6          1.4         0.2    setosa
#> 7           5.4         3.9          1.7         0.4    setosa
#> 8            NA          NA           NA          NA      <NA>
#> 9           6.2         3.4          5.4         2.3 virginica
#> 10          5.9         3.0          5.1         1.8 virginica
#> 11           NA          NA           NA          NA      <NA>
#> 12           NA          NA           NA          NA      <NA>
#> 13           NA          NA           NA          NA      <NA>
#> 14           NA          NA           NA          NA      <NA>
#> 15           NA          NA           NA          NA      <NA>

# looks a little to complicated, but it's late and I'm a bit tired
rm_empty_trailing_rows <- function(df) {
  x <- which(complete.cases(df))
  g <- c(1, cumsum(diff(x) > 1 ) + 1)
  seq_len(max(x[g == max(g)]))  
}

# check that I get the correct rows
df[rm_empty_trailing_rows(df), ]
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
#> 2           5.1         3.5          1.4         0.2    setosa
#> 3           4.9         3.0          1.4         0.2    setosa
#> 4           4.7         3.2          1.3         0.2    setosa
#> 5           4.6         3.1          1.5         0.2    setosa
#> 6           5.0         3.6          1.4         0.2    setosa
#> 7           5.4         3.9          1.7         0.4    setosa
#> 8            NA          NA           NA          NA      <NA>
#> 9           6.2         3.4          5.4         2.3 virginica
#> 10          5.9         3.0          5.1         1.8 virginica
```

**Comment by nicojx** [comment]
Thanks @JanMarvin, that works a treat. I hadn't thought about named regions and selected cells, which make doing this as per default impossible. I agree it can be left to the user.
