### ISSUE TITLE
Writing zero row table results in corrupted workbook

### ISSUE THREAD

**Issue by Napoleongl** [JanMarvin/openxlsx2#676]
I'm converting from openxlsx so that I can add data validation to a workbook. The workbook is going to be used by suppliers to fill in a number of tables in separate sheets. Hence I want to create a number of empty tables with only headers. In openxlsx I could accomplish this by writing a table and indexing zero rows.

Attempting the same thing i openxlsx2 however results in a corrupt workbook where the table is removed and only the text is present.

Code to reproduce:
ttmp <- temp_xlsx()
wb_workbook() %>% 
wb_add_worksheet("table") %>% 
wb_add_data_table("table", data.frame(a=letters[1:3], b = LETTERS[2:4])[1,]) %>%
wb_save(ttmp)
xl_open(ttmp)

Version is 0.7

I'm on a corporate PC so I can only use packages from CRAN (at least I cannot install RTools to compile the github version), but if this by any chance is solved in a non-CRAN-version I guess I'll have to find a way to install it.

This may seem like an error no sane person would run into, and that I'm sort of misusing things, but I can see this happen in scenarios where you don't know if you'll have data to write or not (say you have regional sales and in some period region X didn't sell anything hence the filtered data would have 0 rows). A script that then generates excel files from such a source on a regular basis would then corrupt the output seemingly at random.

**Comment by Napoleongl** [comment]
I should perhaps clarify that the same thing happens writing a filtered dataframe containing no rows, so not only if you manually make sure it has no rows.

**Comment by JanMarvin** [comment]
Hi @Napoleongl , I understand that the above code snippet works, but this breaks? (I can confirm this. Excel does not allow tables with zero rows apparently.)
```R 
wb_add_data_table("table", data.frame(a=letters[1:3], b = LETTERS[2:4])[0,])
```
Whenever you want to create a table with headers in Excel from a single row a second row beneath is used as first row of the table. We can create the same in `openxlsx2` with 
```R
wb_add_data_table("table", x = data.frame(a = NA, b = NA), na.strings = NULL)
```

For convenience, we can use a matrix to define the number of rows we expect in the output table.
``` r
library(openxlsx2)

rows <- 1
nams <- c("a", "b")
mm <- matrix(NA, rows, length(nams), dimnames = list(seq_len(rows), nams)) %>% 
  as.data.frame()

ttmp <- temp_xlsx()
wb_workbook() %>%
  wb_add_worksheet("table") %>%
  wb_add_data_table("table", x = mm, na.strings = NULL) %>%
  wb_save(ttmp)
```

Please let me know if this is what you want to achieve. Maybe a zero row data frame can be added as a workaround, capturing zero rows in `write_data_table()`, adding a second row and setting `na.strings = NULL`.

**Comment by JanMarvin** [comment]
I have opened a PR #677  to handle your initial use case. If a data frame with less than one row is supplied, we will create a warning and fix this for the user. The "correct" way to solve this, is passing a data frame with a single empty row.

**Comment by Napoleongl** [comment]
Hi @JanMarvin !
Thanks for the quick reply.  I had to recheck what happened in openxlsx, and creates the empty row silently, so the result is actually a one row table in Excel. In the end this is the wanted result since I want to add data validation and if I do that in the single empty row the data validation is copied when the table is extended. 
I'll give your matrix-solution a try, I believe it will solve the issue!

**Comment by JanMarvin** [comment]
I have merged the pull request. Thanks for the report!
