### ISSUE TITLE
camel_case to snake_case functions and their arguments

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#679]
## wb
* [x] wb_workbook
  * datetimeCreated
* [x] wb_load
  * xlsxFile

## wb_add & wb_remove functions
* [x] wb_remove_comment / remove_comment
  *  gridExpand
* [x] wb_add_named_region
  * localSheet
  * customMenu
  * functionGroupId
  * localName
  * publishToServer
  * statusBar
  * vbProcedure
  * workbookParameter
* [x] wb_add_cell_style
  * applyAlignment
  * applyBorder
  * applyFill
  * applyFont
  * applyNumberFormat
  * applyProtection
  * borderId
  * extLst
  * fillId
  * fontId
  * justifyLastLine
  * numFmtId
  * pivotButton
  * quotePrefix
  * readingOrder
  * relativeIndent
  * shrinkToFit
  * textRotation
  * wrapText
  * xfId
* [x] wb_add_chart_xml / wb_add_drawing / wb_add_mschart
  * colOffset
  * rowOffset
* [x] wb_add_chartsheet
  * tabColor
* [x] wb_add_data_table
  * startCol
  * startRow
  * colNames
  * rowNames
  * tableStyle
  * tableName
  * withFilter
  * firstColumn
  * lastColumn
  * bandedRows
  * bandedCols
  * applyCellStyle
  * removeCellStyle
* [x] wb_add_data_validation
  * allowBlank
  * showInputMsg
  * showErrorMsg
  * errorStyle
  * errorTitle
  * promptTitle
* [x] wb_add_dxfs_style
  * numFmt
  * bgFill
  * gradientFill
* [x] wb_add_font
  * vertAlign
* [x] wb_add_formula
  * startCol
  * startRow
  * applyCellStyle
  * removeCellStyle
* [x] wb_add_ignore_error
  * wb_add_ignore_error
  * emptyCellReference
  * evalError
  * formulaRange
  * listDataValidation
  * numberStoredAsText
  * twoDigitTextYear
  * unlockedFormula
* [x] wb_add_image / wb_add_plot
  * startRow
  * startCol
  * rowOffset
  * colOffset
* [x]  wb_add_worksheet
  * gridLines
  * rowColHeaders
  * tabColor
  * oddHeader
  * oddFooter
  * evenHeader
  * evenHeader
  * firstHeader
  * firstFooter
  * hasDrawing
  * paperSize
* [x] wb_add_data / write_data
  * startCol
  * startRow
  * colNames
  * rowNames
  * withFilter
  * applyCellStyle
  * removeCellStyle

## wb_get/wb_set functions
* [x] wb_set_base_font
  * fontSize
  * fontColor
  * fontName
* [x] wb_set_bookview
  * activeTab
  * autoFilterDateGrouping
  * firstSheet
  * showHorizontalScroll
  * showSheetTabs
  * showVerticalScroll
  * tabRatio
  * windowHeight
  * windowWidth
  * xWindow
  * yWindow
* [x] wb_set_header_footer
  * evenHeader
  * evenFooter
  * firstHeader
  * firstFooter
* [x] wb_set_sheetview
  * defaultGridColor
  * rightToLeft
  * showFormulas
  * showGridLines
  * showOutlineSymbols
  * showRowColHeaders
  * showRuler
  * showWhiteSpace
  * showZeros
  * tabSelected
  * topLeftCell
  * windowProtection
  * workbookViewId
  * zoomScale
  * zoomScaleNormal
  * zoomScalePageLayoutView
  * zoomScaleSheetLayoutView

## create functions
* [x] create_border
  * diagonalDown
  * diagonalUp
* [x] create_cell_style
  * borderId
  * fillId
  * fontId
  * numFmtId
  * pivotButton
  * quotePrefix
  * xfId
  * justifyLastLine
  * readingOrder
  * relativeIndent
  * shrinkToFit
  * textRotation
  * wrapText
  * extLst
* [x] create_dxfs_style
  * numFmt
  * bgFill
  * fgColor
  * gradientFill
* [x] create_tablestyle
  * wholeTable
  * headerRow
  * totalRow
  * firstColumn
  * lastColumn
  * firstRowStripe
  * secondRowStripe
  * firstColumnStripe
  * secondColumnStripe
  * firstHeaderCell
  * lastHeaderCell
  * firstTotalCell
  * lastTotalCell

**Comment by olivroy** [comment]
Bravo for the great work for unifying fn parameter and cleaning up functions. 

if you'd like, I wouldn't mind going through the vignettes and docs to see where updates could be done

**Comment by JanMarvin** [comment]
:) I figured if I don't rush through it, it will never be done. I did not touch `xlsx_file` or `xlsxFile` yet, but it is not forgotten. The pull request was simply growing larger than what I feel comfortable with (partly because I was throwing in `@noRd` and some argument reordering and deprecations) and we have `xlsxFile` at many places all across the codebase.

I'm not entirely happy with either nor with `file`. Maybe something like `x` is enough. Otherwise we confuse people with files or workbook objects.

**Comment by JanMarvin** [comment]
Every contribution is more than welcome. Especially regarding documentation and testing. It would be kinda miraculous if that large pull request did not break anything, now it's up to us to find these cases and to document changes for the users.

**Comment by JanMarvin** [comment]
Closed in #678
