### ISSUE TITLE
FR: Add `wb_view()`

### ISSUE THREAD

**Issue by olivroy** [JanMarvin/openxlsx2#703]
It may be annoying to type `wb_open(wb)` all the time.

Maybe `wb_view()` could exist, which would take `wb 
```r
wb_view <- function(wb = .Last.value, interactive = NA) { 
  if (is.na(interactive)) 
   interactive <- interactive()
tryCatch(assert_workbook(wb), error = function(e) stop("Specify `wb` or use this function after creating / modifying a `wb` object")) 
wb_open(wb)
}
It could be handy with chaining!
# operations ...
wb_view()
```

Edit: on a related note, does `xl_open()` bring anything more to the table? could be deprecated in favour of `wb_open()` if not.

**Comment by JanMarvin** [comment]
I use `wb$open()`. `xl_open()` opens files.
