### ISSUE TITLE
rework `wbWorkbook$addWorksheet()`

### ISSUE THREAD

**Issue by jmbarbone** [JanMarvin/openxlsx2#71]
Should be appropriate to just accept a `wbWorksheet` object.

```r
addWorksheet = function(worksheet = new_worksheet(), ...)
```

Need to make sure these are all fields in `wbWorksheet`
```r
sheetName,
showGridLines = TRUE
tabColour     = NULL
zoom          = 100
oddHeader     = NULL
oddFooter     = NULL
evenHeader    = NULL
evenFooter    = NULL
firstHeader   = NULL
firstFooter   = NULL
visible       = c("true", "false", "hidden", "visible", "veryhidden")
hasDrawing    = FALSE
paperSize     = 9
orientation   = c("portrait", "landscape")
hdpi          = 300
vdpi          = 300
```

This would help with #9 , #55

**Comment by JanMarvin** [comment]
While this is a neat idea I doubt that it's possible. Worksheets in `openxlsx2` are not independent from the workbook object. While in theory it's possible to move everything into the worksheets (like (pivot) tables, media, charts, drawings, relationships, styles etc.) it would require a lot of coding and testing to implement this and currently I see no benefit to do so.

It might solve a few other issues we have with worksheet dependencies, but obviously it would bring in many more
