### ISSUE TITLE
write_xlsx() parameter sheetName doesn't do anything.

### ISSUE THREAD

**Issue by dereksonderegger** [JanMarvin/openxlsx2#711]
The write_xlsx() function sheetName="Name" parameter does not do anything. Reading into the source code, I tried sheet_name="" as well but that also doesn't work.

    # What version are we running
    packageVersion("openxlsx2")
    #> [1] '0.7.1.9000'

    
    # get a tmp filename
    tmp_file_name <- openxlsx2::temp_xlsx('Test', macros=FALSE)

    
    # Request that the sheetName should be something
    mtcars |>
      openxlsx2::write_xlsx(sheetName = 'MyTestSheet', file = tmp_file_name)

    
    # Open the file
    # openxlsx2::xl_open(tmp_file_name)

    
    # but it used the default sheet name
    openxlsx2::read_xlsx(tmp_file_name, sheet='MyTestSheet') |>
      head()
    #> Error in wb_load(file, sheet = sheet, data_only = TRUE): No such sheet in the workbook. Workbook contains:
    #> Sheet 1

    
    # but it used the default sheet name
    openxlsx2::read_xlsx(tmp_file_name, sheet='Sheet 1') |>
      head()
    #>    mpg cyl disp  hp drat    wt  qsec vs am gear carb
    #> 2 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
    #> 3 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
    #> 4 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
    #> 5 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
    #> 6 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
    #> 7 18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
    Created on 2023-07-31 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by JanMarvin** [comment]
Hi @dereksonderegger , thanks for the report. Looks like I broke something recently. I'll look into it.

**Comment by JanMarvin** [comment]
In the meantime you can use:

```R
wb_workbook()$add_worksheet("MyTestSheet")$add_data(x = mtcars)$save(tmp_file_name)
```

It's a bit unfortunate that people use `write_xlsx()`, but I don't and therefore it breaks all the time :disappointed: Our strength is modifying workbooks, therefore it is merely a helper, wrapping a bunch of functions.

**Comment by JanMarvin** [comment]
https://github.com/JanMarvin/openxlsx2/blob/a0f62ef87da0c67a9e9d3e38941229a35705692a/R/write_xlsx.R#L306-L307

Here we have to assign `sheetName`. Otherwise `names(x)` is Null.

**Comment by dereksonderegger** [comment]
Thanks for doing this! I started using the more interactive functions and that work flow to avoid the issue, but I am grateful for the single function as that is the primary transition function from other packages.  Thanks for all you do here!
