### ISSUE TITLE
Pivot Table breaking bc of dif cases

### ISSUE THREAD

**Issue by lauraearle515** [JanMarvin/openxlsx2#713]
When I try to use the wb_add_pivot_table function with a data set that has the same text but different cases (Berlin vs BERLIN in the example below), the outputted file breaks (no warning messages or errors show up in R). Here's an example that causes the same error I'm facing:
```
library(openxlsx2)
packageVersion("openxlsx2")
#> [1] '0.7.0.9000'

location<- c("London", "NYC", "NYC", "Berlin", "Madrid", "London", "BERLIN")

amount<- c(7, 5, 3, 2.5, 6, 1, 17)
example_df<- data.frame(location, amount)

wb<- wb_workbook() %>% wb_add_worksheet() %>% wb_add_data(x = example_df)
df<- wb_data(wb)
wb<- wb %>% wb_add_pivot_table(df, dims = "A3", rows = "location", data = "amount")

wb$open()
#> Warning in xl_open.default(x$clone()$save(temp_xlsx(macros = has_macros))$path,
#> : will not open file when not interactive
```

<sup>Created on 2023-08-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

which results in this:
![image](https://github.com/JanMarvin/openxlsx2/assets/125679419/c99e6108-1783-484f-aaec-d99e720c5fc0)

which, when I hit yes, loads the data set just fine but where the pivot table should be is blank. 

Now that I've realized that's what is causing the problem, it's not that hard to work around, but it did take a very long time to get to the root of the issue, so some kind of warning that this will cause an issue would be helpful.

**Comment by JanMarvin** [comment]
Hi @lauraearle515 , thanks for the report! I'll look into this. Not sure why it happens.

**Comment by JanMarvin** [comment]
It looks like Excel is merging both in the same `Berlin`. We should be able to come up with a similar logic. Sorry that it took a while, now imagine my pleasure developing this in the first place. Excels error messages are a pleasure to work with 😄, but every report helps so that we all end up with a better tool in the long run!

**Comment by lauraearle515** [comment]
@JanMarvin No need to be sorry, I'm always thrilled with the capabilities of this tool and how quickly you always resolve issues :). Really wasn't a particularly big issue for me, just wanted to make you aware

**Comment by JanMarvin** [comment]
I've added a pull request in #714 that should solve the issue!
