### ISSUE TITLE
Suggestion: Better error message openxlsx2:::assert_workbook

### ISSUE THREAD

**Issue by pteridin** [JanMarvin/openxlsx2#770]
## Background

`openxlsx2:::assert_workbook` is a function that checks the class of workbook-objects before performing operations on it:

```r
function (x) 
 assert_class(x, c("wbWorkbook", "R6"), all = TRUE)
```

I happened to write a `targets` pipeline missing a pipe from one workbook manipulation into the next, resulting in:

`Last error: wb must be class wbWorkbook or R6`

Which I find to be a little confusing.

## Suggestion

I think it would be nice to check for missing wb before asserting class, thus throwing a more precise error message, something along the way of:

```r
check <- function (wb) {
     if(hasArg(wb) == FALSE)
         stop("Workbook `wb` is missing")
     assert_class(wb, c("wbWorkbook", "R6"), all = TRUE)
 }
 
```

**Comment by JanMarvin** [comment]
I cannot say that I have a strong opinion on this. But I guess we integrate this into `assert_workbook()`? (I wasn't aware of `hasArg()` previously.)

``` r
assert <- function(wb) {
  if (!hasArg(wb)) stop("did not found wb")
  print("all good!")
}

assert()
#> Error in assert(): did not found wb
assert(wb = 1)
#> [1] "all good!"
assert(1)
#> [1] "all good!"
wb <- substitute()
assert(wb)
#> Error in assert(wb): did not found wb
wb <- 1
assert(wb)
#> [1] "all good!"
```

Otherwise we'd have to add a bunch of `if (missing(wb)) stop(...)` checks into our wrapper pipes and I'd really dislike that.

**Comment by JanMarvin** [comment]
I have tried to add this into #772

**Comment by pteridin** [comment]
Thank you 👍 

At least I was confused by the error message. Tought that I fiddled with the class of the workbook somewhere along the lines by accident. And the cascades of "Why? Where?" questions started in my head. 😄

**Comment by JanMarvin** [comment]
Yeah, don't get to addicted to piping ;)

**Comment by pteridin** [comment]
Too late. 🤣
