### ISSUE TITLE
stio exception thrown on writing excel sheet

### ISSUE THREAD

**Issue by skirsch** [JanMarvin/openxlsx2#773]
There is an uncaught stoi exception that is thrown when writing a workbook.

this happened to me awhile ago and was repeatable. 

I think it happens when there is a column with mostly numbers as integers and then there is a bogus dataentry problem with a string that can't be converted.

So think of a providerNum column with the following data:

123445
124423432
234A234     <<<< this cell likely generates the exception
23432432

If you can't find this, i can try to replicate. I had to stop using the package entirely due to this error.

**Comment by JanMarvin** [comment]
We have 3 cases, where `std::stoi()` is used directly, otherwise we use R functions for string to numeric conversions. Two times to convert the row id in `xml_sheet_data()`.

**Comment by skirsch** [comment]
Wow. thanks for the quick response. I'll try it again and send you the full dump. Turns out that xlsx library can't handle my dataframes either.

**Comment by skirsch** [comment]
OK, I switched back to using your library and IT WORKED LIKE A CHARM.

NO ERRORS.

THANK YOU!!!

I CAN'T THANK YOU ENOUGH!!!!!!!!!!!!!!

**Comment by JanMarvin** [comment]
Thanks for the reply and glad that it's solved! The list of things that we've worked on in the last few months is quite massive, therefore it might have been fixed sometime earlier this year.

Obviously there are bugs in complex software like `openxlsx2`, so please reach out again if you encounter any. At best with some minimal reproduce able example.
