### ISSUE TITLE
Excel throws an error- "Removed Records: View from /xl/workbook.xml part (Workbook)"

### ISSUE THREAD

**Issue by chowmun63** [JanMarvin/openxlsx2#792]
I loaded a workbook from my local drive, delete a worksheet and save the workbook. When I tried to open the workbook by double-clicking the output file, Excel threw an error.

If I added a new worksheet, keeping the total number of worksheet same as the loaded workbook, no error was encountered.

The version of openxlsx2 is 1.0.
The version of R is 4.3.0.

Here is the reprex.

``` r
library(openxlsx2)
#> Warning: package 'openxlsx2' was built under R version 4.3.1

# Excel prompts error when the file is being opened
wb <- wb_load("test file.xlsx")
#> Error in wb_load("test file.xlsx"): File does not exist.
wb$get_sheet_names()
#> Error in eval(expr, envir, enclos): object 'wb' not found
wb$remove_worksheet(1)
#> Error in eval(expr, envir, enclos): object 'wb' not found
wb$get_sheet_names()
#> Error in eval(expr, envir, enclos): object 'wb' not found
wb_save(wb, "test_out.xlsx")
#> Error in eval(expr, envir, enclos): object 'wb' not found

# {no error
wb <- wb_load("test file.xlsx")
#> Error in wb_load("test file.xlsx"): File does not exist.
wb$get_sheet_names()
#> Error in eval(expr, envir, enclos): object 'wb' not found
wb$remove_worksheet(1)
#> Error in eval(expr, envir, enclos): object 'wb' not found
wb$get_sheet_names()
#> Error in eval(expr, envir, enclos): object 'wb' not found
wb$add_worksheet("new1")
#> Error in eval(expr, envir, enclos): object 'wb' not found
wb$get_sheet_names()
#> Error in eval(expr, envir, enclos): object 'wb' not found
wb_save(wb, "test_out.xlsx")
#> Error in eval(expr, envir, enclos): object 'wb' not found
# }
```

<sup>Created on 2023-09-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
![Excel's error message](https://github.com/JanMarvin/openxlsx2/assets/44160210/7755734b-7c54-4956-8ec1-27c3437d0419)
[test file.xlsx](https://github.com/JanMarvin/openxlsx2/files/12571127/test.file.xlsx)

**Comment by JanMarvin** [comment]
Hi @chowmun63 , thanks for the report. Looks like we do not pop the worksheet view when removing the worksheet.
