### ISSUE TITLE
the state of stringi

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#80]
Having moved imports in https://github.com/JanMarvin/openxlsx2/commit/f88f99519f01052bc4a4505fdab5a6cb6ffab2e5 I wondered, if we still need the `stringi` dependency or if we should continue to strengthen its use.

Previously somebody complained, that `c()` and `paste/0()` are slow, and introduced `stringi` to the package. Is this still a valid claim? Especially because I have not taken care of it, we currently have a mix of both worlds. Should we move the remaining `c()` and friends to `stringi` or should we ditch `stringi` altogether?

Right now, the only advantage I see is that we have slightly better unicode support on non utf8 Windows, but hopefully this will be fixed with the Windows unicode only R releases.

```R
# from NAMESPACE
importFrom(stringi,stri_c)
importFrom(stringi,stri_conv)
importFrom(stringi,stri_isempty)
importFrom(stringi,stri_join)
importFrom(stringi,stri_match)
importFrom(stringi,stri_replace_all_fixed)
importFrom(stringi,stri_split_fixed)
importFrom(stringi,stri_sub)
```

**Comment by jmbarbone** [comment]
So, many of our string manipulation with `gsub()` and `regmatches()` utilize perl expressions which isn't supported in `stringi`.

This is how I see it, we can do one of these:

* rewrite the string searches to no longer use perl expression
* use base R where we need perl expressions, replace what we can with `stringi`
* remove `stringi`

The first one seems more time expensive and possibly problematic.  Keeping `stringi` where we can could be beneficial but I don't know by how much or if it would be worth the trouble of including the dependency.  I don't think the string operations are our biggest slowdown.

**Comment by JanMarvin** [comment]
I have been thinking about this a bit lately and discussed it over a few beers earlier this week when I visited a friend in Munich. I did some tests with `profvis` (the profiler that RStudio comes with) and using `stringi` was indeed helpful. However, I would not invest much time in forcing or converting to/from `stringi`. It's just not worth the effort. After all, this isn't competitive programming and I'm not going to lose sleep over a few wasted milliseconds. Especially not if it takes a few hours of development work on my part. As long as we don't see or feel that we are slow or are pointed out by users, we shouldn't waste our time optimizing some artificial benchmarks.

**Comment by JanMarvin** [comment]
After merging #173 (increased loading time) and #178 (decreased loading time) we're at:

```R
> xlsxFile <- system.file("extdata", "readTest.xlsx", package = "openxlsx2")
>
> xlsx_new <- openxlsx::temp_xlsx()
> xlsx_old <- openxlsx2::temp_xlsx()
> wb_old <- openxlsx::loadWorkbook(xlsxFile)
> wb_new <- openxlsx2::wb_load(xlsxFile)
>
> sheet <- 5 # large sheet 271 x 297. With more columns than rows and we are still a bit slow creating long_to_wide
Unit: milliseconds
                                                   expr       min        lq      mean    median        uq       max neval
             wb_old <- openxlsx::loadWorkbook(xlsxFile) 117.06906 121.93002 125.00688 124.12016 127.09787 140.59572    25
                 wb_new <- openxlsx2::wb_load(xlsxFile)  77.49894  82.88466  88.44689  86.89495  91.82446 108.19031    25
    x_old <- openxlsx::read.xlsx(wb_old, sheet = sheet)  11.91993  12.83833  14.93066  13.58892  16.05548  30.48112    25
   x_new <- openxlsx2::read_xlsx(wb_new, sheet = sheet)  62.33648  64.52658  78.70571  68.56979  83.40298 131.60475    25
         openxlsx::saveWorkbook(wb_old, xlsx_old, TRUE) 332.48864 347.91272 367.21375 355.74601 369.73673 526.97620    25
             openxlsx2::wb_save(wb_new, xlsx_new, TRUE) 232.77114 241.03814 256.42354 252.86414 255.83221 304.76895    25
  x_old <- openxlsx::read.xlsx(xlsxFile, sheet = sheet)  77.80480  82.31591  89.16942  84.56348  89.28549 145.26382    25
 x_new <- openxlsx2::read_xlsx(xlsxFile, sheet = sheet) 120.41852 126.09833 147.42198 135.29242 177.04768 189.69425    25
```

**Comment by jmbarbone** [comment]
Probably good to close? I think most of the base functions in here have been replaced with `{stringi}` by now.

**Comment by JanMarvin** [comment]
yeah, it was open solely for the benchmarks
