### ISSUE TITLE
wb_update_table doesn't work with tables with no filter

### ISSUE THREAD

**Issue by sxl634** [JanMarvin/openxlsx2#802]
If you use wb_update_table which does not have an auto filter, you'll get the following error: 
* Error: Expecting a single string value: [type=character; extent=0].

In the documentation, the following example is used and works:
``` 
wb <- wb_workbook()$add_worksheet()$add_data_table(x = mtcars)
wb$update_table(tabname = "Table1", dims = "A1:J4")
```

However, if you adjust this example such that no filter is provided when adding the data table as seen below, you get the error mentioned above:
```
wb <- wb_workbook()$add_worksheet()$add_data_table(x = mtcars, with_filter = FALSE)
wb$update_table(tabname = "Table1", dims = "A1:J4")
```

This is because the autofilter node does not exist, but the wb_update_table function requires there to be an autofilter. Can this be fixed such that an autofilter is not required?

**Comment by JanMarvin** [comment]
A potential fix is in main. Could you check if this solves your problem @sxl634 ?

PS: There might be other xml nodes for tables, maybe I'll add a follow up commit to check if we got all nodes.

**Comment by sxl634** [comment]
Looks like it worked based on the example I used! Thanks @JanMarvin! V impressed with the speedy fix. Will let you know if I encounter anything else, really liking the package so far!
