### ISSUE TITLE
Using relative indent  throws error

### ISSUE THREAD

**Issue by JahNorr** [JanMarvin/openxlsx2#824]
I’m getting an error thrown when I use relative_indent when styling. (Error: object 'zz' not found) I looked at the code and it seems like one of your functions, set_cellstyle, references an object named zz that doesn’t exist. You have about twenty references to an object named z, but in the middle of this is one reference to zz. It looks like a typo. 

It’s wb_styles.R, line 613

**Comment by JanMarvin** [comment]
Thanks for the report, @JahNorr ! A fix is #825. Though, I double checked with the [manual](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.alignment?view=openxml-2.8.1), `relativeIndent` is only used in `dxfs` for normal cell styles the following works:

``` r
library(openxlsx2)

wb <- wb_workbook() %>% 
  wb_add_worksheet() %>% 
  wb_add_data(x = c("foo", "bar")) %>% 
  wb_add_cell_style(
    dims = "A2",
    indent = 1
  )
if (interactive()) wb$open()
```

**Comment by JanMarvin** [comment]
Fix is in main and will be in the next release. Thanks again!

**Comment by JahNorr** [comment]
Thank you ... still getting comfortable with openxlsx2 syntax. Feel it's the best excel package out there.

**Comment by JanMarvin** [comment]
Thanks for the kind words! As mentioned [elsewhere](https://janmarvin.github.io/ox2-book/chapters/01_introduction.html), there are plenty of tasks that can be solved with the xlsx file format and all packages have their strengths and weaknesses, but we certainly fill our niche :)
