### ISSUE TITLE
Adding a table where a column contains a formular with "<" results in an error.

### ISSUE THREAD

**Issue by mrainers** [JanMarvin/openxlsx2#841]
Let's say we want to add a table, where one column is an excel formula a suggested (and really nice) way to do so, is to add  a "formula" class to that column:

```r
wb <- wb_workbook()
wb$add_worksheet()

df = data.frame(x = 10,
                f = "A1<5")

class(df[["f"]]) <- c(class(df[["f"]]), "formula")

wb$add_data(x = df)

wb$open()
```

This works as long the formular does not contain a smaller than sign `<`. If it does, excel throws an error when trying to open the workbook.

The function `wb$add_formula(x = "A1<5", dims = "B2")` however works perfectly fine. 

I guess this has something to do with parsing of the angle brackets?

### Version Info
openxlsx2 : 1.1

**Comment by JanMarvin** [comment]
Thanks for the report @mrainers, but this was fixed with your last bug report.

``` r
library(openxlsx2)
wb <- wb_workbook()
wb$add_worksheet()

df = data.frame(x = 10,
                f = "A1<5")

class(df[["f"]]) <- c(class(df[["f"]]), "formula")

wb$add_data(x = df)

# works
wb$worksheets[[1]]$sheet_data$cc$f[4]
#> [1] "A1&lt;5"
```

**Comment by JanMarvin** [comment]
Previous to the fix in #834 we would try to write "A1<5", which is not valid xml. The fix escapes the `"<"` correctly as `"&lt;"`.

**Comment by mrainers** [comment]
Allright, got the latest developement version and now it works :-)

**Comment by JanMarvin** [comment]
Glad you got it working! And sorry, apparently I was a little confused yesterday. #834 fixes a similar issue, but wasn't raised by you, but [David Weisser on stackoverflow](https://stackoverflow.com/q/77379858/12340029). Until the next release is deployed to CRAN, you could also write `"A1 &lt; 5"` in your formula. This escaped string will also be valid in future releases.
