### ISSUE TITLE
Coping data doesn't copy hyperlinks 

### ISSUE THREAD

**Issue by Turtle6665** [JanMarvin/openxlsx2#846]
I am encountering a problem with the `openxlsx2` package when attempting to copy cells containing hyperlinks which links to a URL within an Excel file. After performing the copy operation, the hyperlinks seem to be lost in the target cells.

**Steps to reproduce:**
1. make a xlsx file containing Hyperlinks to URLs in the first 4 cells ("A1:B2"). I find the easiest way is to copy a hyperlink from a Wikipedia page. Just make sure that once copied, you can click on the links, and it redirects you to the webpage.
2. Save this file as "example.xlsx"
3. Run the following code. It opens first the unmodified xlsx file. It then copies the cells "A1:B2"

``` r
remotes::install_github("JanMarvin/openxlsx2")
library("openxlsx2")
packageVersion("openxlsx2")
#> [1] '1.1.0.9000'

# Load the created example Excel file
wb_in <- wb_load("example.xlsx")
xl_open(wb_in)
#> Warning: will not open file when not interactive
#> NULL

# Extract data from the specified range
dat <- wb_data(wb_in, 1, dims = "A1:B2", col_names = FALSE)

# Paste the extracted data
wb_in$copy_cells(data = dat, dims = "D1")

# View the worksheet to observe the issue
xl_open(wb_in)
#> Warning: will not open file when not interactive
#> NULL
```

**The output of the last xl_open(wb_in):**
The columns A and B contains URLs while the D and E don't (but have the same styling)
![image](https://github.com/JanMarvin/openxlsx2/assets/110727570/26633a58-73d1-44e5-8265-98776b8cd9f2)

**The expected behavior**
I feel like the hyperlinks should be copied at the same time as the formatting/style. 

I couldn't find any workaround to perform exactly that and as the links are only in the hyperlinks and not in the text, I really need to be able to copy the hyperlinks.

If you have any idea on how could I make it work, please, let me know.

**Comment by JanMarvin** [comment]
Hi @Turtle6665 , I assume this is due to the hyperlink in relationships. I’ll have a look later.

**Comment by JanMarvin** [comment]
The issue can be solved like this, but I'm a little tired to create a pull request for this right now and have no time this weekend. Has to wait for next week:

``` r
library(openxlsx2)

# an example file with an external hyperlink
wb_in <- wb_load("https://github.com/JanMarvin/openxlsx-data/raw/main/Single_hyperlink.xlsx")

# Extract data from the specified range
dat <- wb_data(wb_in, 1, dims = "A1", col_names = FALSE)

# Paste the extracted data
wb_in$copy_cells(data = dat, dims = "A3")

### integrate this into the wb_copy_cells() function ---
hyperlink_in_wb <- vapply(
  wb_in$worksheets[[1]]$hyperlinks, 
  function(x) x$ref,
  NA_character_
)

cells_in_range <- unname(unlist(attr(dat, "dims")))

if (any(hyperlink_in_wb %in% cells_in_range)) {
  # do some magic ...
  
  # prepare the updated link
  hl <- wb_in$worksheets[[1]]$hyperlinks[[1]]$clone()
  hl$ref <- "A3"
  
  # assign it
  wb_in$worksheets[[1]]$hyperlinks <- append(
    wb_in$worksheets[[1]]$hyperlinks,
    hl
  )
}

# View the worksheet to observe the issue
if (interactive()) wb_in$open()
```

**Comment by JanMarvin** [comment]
We have to get the original cell of the hyperlink and the new position of it (even if transposed).

There are two ways to create hyperlinks in openxml. Either as formula (we do this) or in workbook relationships (Excel does this). Not sure what’s the benefit, but since I rarely work with hyperlinks it was overlooked.

**Comment by JanMarvin** [comment]
@Turtle6665 , this should be fixed now in main. Could you give this a test in the coming days to see if your issue is solved?
