### ISSUE TITLE
Copy cells `as_values` could use `na.strings` argument

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#852]
We’re using `wb_add_data()` internally

**Comment by olivroy** [comment]
Maybe add example?

Let me know which newer features are worthy of adding to vignettes / examples.

I could work on that early next week if you'd like.

**Comment by JanMarvin** [comment]
Thanks, I’ll think about it. Guess copy cells isn’t documented at all at the moment, even though it’s a neat feature. Similar copying worksheets across workbooks and pivot tables could use some more documentation in vignettes. I might open a new issue and assign you.

**Comment by JanMarvin** [comment]
An example for this feature. Wanted to craft a unit test from this, but comparing all of `cc` seemed a bit over dramatic. 

``` r
library(openxlsx2)

mm <- matrix(1:6, 2, 3)
wb_in <- wb_workbook()$add_worksheet()$add_data(x = mm, col_names = FALSE)

dat <- wb_data(wb_in, 1, dims = "A1:C3", col_names = FALSE)
wb_in$copy_cells(data = dat, dims = "A4")

dat <- wb_data(wb_in, 1, dims = "A1:C3", col_names = FALSE)
wb_in$copy_cells(data = dat, dims = "D1", transpose = TRUE)

wb_in$copy_cells(data = dat, dims = "D4", transpose = TRUE, as_ref = TRUE)
wb_in$copy_cells(data = dat, dims = "D7", transpose = TRUE, as_value = TRUE, na.strings = "N/A")

# wb_in$worksheets[[1]]$sheet_data$cc

if (interactive()) wb_in$open()
```
