### ISSUE TITLE
Can't write fmt_text output to header cell

### ISSUE THREAD

**Issue by alanault** [JanMarvin/openxlsx2#915]
Hi

I'm trying to use fmt_text to create a new header/col_name which has different colour text. While I can write the formatted text to the workbook, it won't appear in the header even when a top row (e.g. B1) cell is selected. See example below

```
# toy example
library(openxlsx2)
wb <- wb_workbook() %>%
  wb_add_worksheet("test") %>%
  wb_add_data(x = mtcars)

# create string
new_header <- fmt_txt("hello ", color = wb_color("red")) + fmt_txt("world", color = wb_color("green"))

# add to workbook
wb <- wb_add_data(wb, sheet = "test", x = new_header, dims = "B1")

# write 
openxlsx2::wb_save(wb, "test.xlsx")

```

The resulting XLSX file puts this string into B2, rather than B1. I've tried all types of combinations with wb_dims, but can't seem to get it to write to the header?

<img width="610" alt="Screenshot 2024-01-27 at 10 55 29" src="https://github.com/JanMarvin/openxlsx2/assets/8653082/17661060-b66a-41e1-b4a0-fc8bbdff062c">

**Comment by JanMarvin** [comment]
Hi @alanault , could you try `col_names = FALSE`?

**Comment by alanault** [comment]
That worked perfectly! Thanks so much for the fast response!

**Comment by JanMarvin** [comment]
Glad that it works!

**Comment by JanMarvin** [comment]
Apparently fmt txt is interpreted as data frame. I can have a detailed look later
