### ISSUE TITLE
`dims` are not converted in `wb_add_image()`

### ISSUE THREAD

**Issue by olivroy** [JanMarvin/openxlsx2#952]
Looks like you found a bug. We never convert to `dims` in `wb_add_image()`:

https://github.com/JanMarvin/openxlsx2/blob/ee3590b2ac30dd17a646ccef450aa8fb7399d514/R/class-workbook.R#L4915-L4922

Should be a simple fix using dims and `wb_dims()`.

_Originally posted by @JanMarvin in https://github.com/JanMarvin/openxlsx2/discussions/948#discussioncomment-8528225_

**Comment by JanMarvin** [comment]
Thanks for tracking. I've opened a PR in #953. It's a tad bit sad that we have to fix a deprecated call, instead of removing it, but that's life.
