### ISSUE TITLE
wb_add_ignore_error() function not found

### ISSUE THREAD

**Issue by Stochos** [JanMarvin/openxlsx2#954]
Good day,

Maybe I'm missing something, but after I load openxlsx2, the function wb_add_ignore_error() is not loaded. However the help file is visible. 

openxlsx2 version 1.4

**Comment by JanMarvin** [comment]
Hi @Stochos , thanks for the report. Indeed the export was overlooked. You can use the workbook function `wb$add_ignore_error()` or `openxlsx2:::wb_add_ignore_error()`.

**Comment by Stochos** [comment]
I will do.
Thank you for a great package and your speedy response.

**Comment by JanMarvin** [comment]
Thanks for the kind words!
