### ISSUE TITLE
Review file name in workbook examples

### ISSUE THREAD

**Issue by jmbarbone** [JanMarvin/openxlsx2#96]
We may not need the `wb_save(wb, "example_name.xlsx")` in every example but we may at least have to change the file names after updating the function names.

May possibly be able to play around with `interactive()` to only save/open the workbooks during an active session

_Originally posted by @JanMarvin in https://github.com/JanMarvin/openxlsx2/pull/82#discussion_r826646394_

**Comment by JanMarvin** [comment]
All file names are gone as requested by CRAN. Closing this.
