### ISSUE TITLE
[docs] CRAN warning regarding html

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#969]
https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/openxlsx2-00check.html

```
checking HTML version of manual ... [8s/17s] NOTE
Found the following HTML validation problems:
convert_date.html:55:1 (convert_date.Rd:23): Warning: trimming empty <dt>
```

**Comment by JanMarvin** [comment]
Looks like an R issue

https://github.com/JanMarvin/openxlsx2/blob/95abe2935f67872885a5f9b02eab8cd8b6725faa/R/dates.R#L11

**Comment by JanMarvin** [comment]
Or probably a roxygen2 issue

**Comment by olivroy** [comment]
do you know which arguments cause problem 
```

#' @inheritDotParams base::as.Date -arg1 -arg2

```

**Comment by JanMarvin** [comment]
Hi @olivroy , no not yet. I’m traveling for the weekend and only have access to my smartphone right now. It looked like some new line was inserted after `base::as.Date`. We might have to create a custom parameter description for the time being, or patch the html file.

![Convert from Excel date, datetime or hms number t…](https://github.com/JanMarvin/openxlsx2/assets/1645626/f852f699-3ea2-4123-9855-33867a4284ef)

**Comment by olivroy** [comment]
looking at the signature, maybe this will work
```
#' @inheritDotParams base::as.Date.character
```
