### ISSUE TITLE
wb_add_ignore_error is not an exported object from namespace:openxlsx2

### ISSUE THREAD

**Issue by dom-simard** [JanMarvin/openxlsx2#975]
Unless I'm missing something, it looks like wb_add_ignore_error() is not being exported in version 1.4. I'm getting "Error: 'wb_add_ignore_error' is not an exported object from 'namespace:openxlsx2'''

**Comment by JanMarvin** [comment]
Hi @dom-simard , thanks for the report. That’s already fixed in the main branch and will be in the next release (see also #955 ). The next release will probably happen end of next week.
