### ISSUE TITLE
writing an empty data frame containing date variables results in "Error: stoi"

### ISSUE THREAD

**Issue by Obihoernchen80** [JanMarvin/openxlsx2#985]
**Detected in**
> packageVersion("openxlsx2")
[1] ‘1.4’

**Confirmed in**
> packageVersion("openxlsx2")
[1] ‘1.5.0.9000

**Reprex**
data.frame(date=base::as.Date(NULL))   |> openxlsx2::write_xlsx("test.xlsx")
data.frame(date=lubridate::POSIXct(0)) |> openxlsx2::write_xlsx("test.xlsx")
data.frame(date=lubridate::date(NULL)) |> openxlsx2::write_xlsx("test.xlsx")

**Issue**
In all cases, no file gets saved, the error message is "Error: stoi".
The issue occurs if the data frame has 0 rows and contains at least one date-type variable.
The issue does not occur if write_xlsx is called with "as_table=T"

**Comment by olivroy** [comment]
@JanMarvin I saw this error in another context, maybe due to this?
https://github.com/JanMarvin/openxlsx2/blob/1194783925e368072b992e042d614a67be6623b5/R/utils.R#L180-L182

**Comment by Obihoernchen80** [comment]
@olivroy 

I tracked it up to here, where col2int fails due to col being an empty string (somehow created by adding missing ros I presume)
https://github.com/JanMarvin/openxlsx2/blob/1194783925e368072b992e042d614a67be6623b5/R/write.R#L73C4-L73C71

**Comment by JanMarvin** [comment]
@Obihoernchen80 , thanks for the report. I assume that's ultimately due to

```R
data.frame(date = base::as.Date(NULL)) |> 
  NROW()
#> [1] 0
```

We probably do not handle this corner case well enough, but I have to look into it.

**Comment by JanMarvin** [comment]
Okay, got it. The issue stems from `add_numfmt()` which is required, because `as.Date()` needs a `numformat`. Our write function checks for missing cells required, which in this case returns `dim_sel <- ""`. This is passed further down until it finally bails in `col2int()`.

``` r
library(openxlsx2)
col2int("")
#> Error in eval(expr, envir, enclos): stoi: no conversion
```

**Comment by Obihoernchen80** [comment]
> We probably do not handle this corner case well enough, but I have to look into it.

"corner case" sounds like it may not happen too often (which may be why the bug was not reported earlier), but let me mention that my scenario is outputting records that failed validation - so an empty data frame is what you hope for :-)

Anyhow, thanks for looking into this!

**Comment by JanMarvin** [comment]
Yes, sorry, that wasn't meant to be judgmental. It's just that we haven't seen this in over 2 years and obviously no one has complained. I opened a PR in #987 that was supposed to fix this error. It turns off the application of styles to a data frame with no rows.

**Comment by JanMarvin** [comment]
Thanks again for reporting, the fix is now in `main` and will be in the next release
