### ISSUE TITLE
Catch incorrect wb_dims

### ISSUE THREAD

**Issue by JanMarvin** [JanMarvin/openxlsx2#988]
Thanks for the report, we will investigate!

@JanMarvin I saw this error in another context, maybe due to this?
https://github.com/JanMarvin/openxlsx2/blob/1194783925e368072b992e042d614a67be6623b5/R/utils.R#L180-L182

_Originally posted by @olivroy in https://github.com/JanMarvin/openxlsx2/issues/985#issuecomment-2049822888_

**Comment by JanMarvin** [comment]
I guess this happens if the input is a dimension without a column attribute? We might have to check if the first character is part of LETTERS (and hope that LETTERS is not localized).

Do you have an example where you ran into this problem, @olivroy ?

**Comment by olivroy** [comment]
not really, it was while dev, never saw it IRL

**Comment by JanMarvin** [comment]
Okay, maybe this is now already covered in `wb_dims()`.

A few strange, but unrelated `wb_dims()` calls ...

```R
> wb_dims(x = mtcars, cols = "25")
[1] "Y2:Y33"
> wb_dims(x = mtcars, cols = "Brrrm")
[1] "BRRRM2:BRRRM33"
> wb_dims(x = data.frame())
[1] "MWLQKWU1:1"
Warning messages:
1: In min(col_int) : no non-missing arguments to min; returning Inf
2: In max(col_int) : no non-missing arguments to max; returning -Inf
```

**Comment by olivroy** [comment]
I can fix those!

**Comment by JanMarvin** [comment]
Thanks, that would be great. I've opened another PR in #989
