### ISSUE TITLE
Freeze top row

### ISSUE THREAD

**Issue by vojtechhuser** [JanMarvin/openxlsx2#998]
I am using writexl package but it does not support some features.

Can you please put into a  vignette example how to freeze top row.  (or as answer on SO) (or here) (but this is a question rather than issue)

See for context https://stackoverflow.com/questions/56499277/r-how-can-you-freeze-the-top-row-in-an-exported-excel-file-using-r-code

**Comment by olivroy** [comment]
Hi, please find documentation on [our website](https://janmarvin.github.io/openxlsx2/reference/wb_freeze_pane.html). Feel free to let us know if you have suggestions for improvement!.


```r
library(openxlsx2)
# create workbook object
wb <- wb_workbook()
# add a new sheet
wb$add_worksheet("sheet")
# add data to show
wb$add_data(x = mtcars)
# indicate which to do
# see more in ?wb_freeze_pane
wb$freeze_pane(
  first_row = TRUE
)
# visualize the result
wb$open()
```

As you can see, the first row is frozen.
![image](https://github.com/JanMarvin/openxlsx2/assets/52606734/ce139823-a184-4be0-8009-9f568950e03d)
